# Nemesis / Gradius (Konami, RC-742, 1986, MSX1) - disassembly
#
# Built with Nestor80 the same way as Nextor: every logical module in src/ is
# assembled on its own with N80 into a relocatable file, and LK80 links them
# and puts each one in place. `make verify` checks that the result is the
# original cartridge, byte for byte (by its SHA-256: the original ROM is not
# needed for that).
#
# THE UNIT OF THE LINK IS THE IMAGE, NOT THE ROM BANK. This is a 128 KB MegaROM
# with the Konami mapper without SCC (Konami4): 16 banks of 8 KB, switched in
# at 0x6000, 0x8000 and 0xA000 (bank 0 is fixed at 0x4000). An image is a set
# of banks that the game always maps together, so for the CPU it is one
# stretch of memory; each image is linked in one LK80 run and its modules may
# cross from one bank into the next.
#
#   image     banks   address           what it is
#   main      0-3     0x4000-0xBFFF     the game, in the layout INIT sets up
#   scenery   4-6     0x6000-0xBFFF     the scenery graphics and their records
#   sound     7-8     0x8000-0xBFFF     the sound player and the sounds
#   screens   9-10    0x8000-0xBFFF     the fixed screens and their engine
#   map       11-12   0x8000-0xBFFF     the map pieces and the stage scripts
#
# Bank 6 (inside the scenery image) is 0xFF from end to end: it is mapped
# together with 4 and 5, but nobody reads it. Banks 13, 14 and 15 are 0xFF too
# and no mapper write ever selects them; they have no source at all. Every
# 0xFF filler of the cartridge is generated by LK80 (--fill 0FFh), not written
# in the sources.
#
# The images are in bank order, so the ROM is just their concatenation plus
# the three empty banks.
#
# The main image calls into two of the others (the sound player and the
# fixed-screens engine). Those are linked first, and each writes the symbols
# that main uses into build/inc/<image>_symbols.inc.

N80      ?= N80
LK80     ?= LK80
SRC      = src
BUILD    = build
ROM      = $(BUILD)/nemesis.rom
SHA      = 3210f8a0f2309dd4b9a89fc2b24d0f178ce4393a0a1f2854fbce545c361261bc

N80_ARGS  = --build-type rel --no-show-banner --verbosity 0 \
            --include-directory $(SRC)/inc --include-directory $(BUILD)/inc
LK80_ARGS = --no-show-banner --output-format bin --fill 0FFh --end 0BFFFh

# Link order is address order: each module goes right after the previous one.
# A module preceded by @<address> is placed at that address instead, and the
# gap before it is filled with 0xFF.
MAIN = cartridge_header interrupt dispatcher init game_start stage_graphics \
       pause_and_frame scroll_and_sprites country_check shrapnel \
       other_cartridge cheats vdp_setup title_screen demo \
       enemy_movers enemy_aim spawn_object shot_speed stage_ends \
       music_by_distance shot_collisions boss \
       bosses piece_route homing_table map_collisions ship_drawing \
       joystick_directions ship_speed options \
       power_up_meter cheat_effects laser enemy_waves single_file_wave \
       enemy_marks boss_death_fade enemy_types tilting_enemy turning_enemy \
       walking_enemy rock_rain rock_walls figure_eight_enemy stage7_script \
       blinking bonus_target three_shot_fan stage5_background \
       stage5_characters stage5_second_script spiral_enemy three_slot_enemy \
       moving_background changing_cells @0BFF5h konami_mark
SCENERY = graphics records
SOUND   = repeat_command psg_mix play channels interpreter melody \
          sound_table sound_data
SCREENS = fixed_screens screen_graphics screen_engine
MAP     = pieces scripts

ORG_main    = 4000h
ORG_scenery = 6000h
ORG_sound   = 8000h
ORG_screens = 8000h
ORG_map     = 8000h

# What each image exports to the main image.
EXPORTS_map = ^(endings_table|pieces_A|pieces_B|script_table)$$
EXPORTS_scenery = ^(common_records|extra_records_1|extra_records_2|graphics_1D00|graphics_chain_6000|graphics_chain_6379|graphics_chain_7793|graphics_colours_30A8|graphics_names_1800|graphics_patterns_10A8|graphics_patterns_1160|list_for_0x4348|record_lists_A|record_lists_B|record_lists_C|stage_graphics_blocks|trigger_records)$$
EXPORTS_screens = ^(data_AAB0|graphics_0468|graphics_2468|graphics_9B3F|graphics_9BCB|graphics_colours_0418|graphics_colours_0780|graphics_colours_2008|graphics_colours_2808|graphics_colours_3008|graphics_patterns_0008|graphics_patterns_0808|graphics_patterns_1008|graphics_patterns_2418|graphics_patterns_2780|graphics_sprites_1800|graphics_sprites_1800_b|name_table_screen|run_screen|set_up_screen|type_3_piece_drawings)$$
EXPORTS_sound = ^(play|sound_table)$$

IMAGES = main scenery sound screens map

all: verify sanity test

# ------------------------------------------------------------------ assembling

rels = $(addprefix $(BUILD)/$(1)/,$(addsuffix .rel,$(filter-out @%,$(2))))
link_items = $(foreach m,$(2),$(if $(filter @%,$(m)),--code $(patsubst @%,%,$(m)),$(BUILD)/$(1)/$(m).rel))

define IMAGE_RULES
$(BUILD)/$(1)/%.rel: $(SRC)/$(1)/%.asm $(wildcard $(SRC)/inc/*.inc) $(3) | $(BUILD)/$(1) $(BUILD)/inc
	$$(N80) $$< $$@ $$(N80_ARGS) --listing-file $$(@:.rel=.lst)

$(BUILD)/$(1):
	mkdir -p $$@

# One link for the whole image. The verbose output is kept as the link map:
# it says where each module ended up.
$(BUILD)/$(1).bin $(BUILD)/$(1).map &: $(call rels,$(1),$(2)) | $(BUILD)/inc
	$$(LK80) $$(LK80_ARGS) --verbosity 3 --code $$(ORG_$(1)) \
	         $(call link_items,$(1),$(2)) --output-file $(BUILD)/$(1).bin \
	         $$(if $$(EXPORTS_$(1)),--symbols-file $(BUILD)/inc/$(1)_symbols.inc \
	           --symbols-file-format equs --symbols-file-regex "$$(EXPORTS_$(1))") \
	         > $(BUILD)/$(1).map || { cat $(BUILD)/$(1).map; rm -f $(BUILD)/$(1).map; exit 1; }
endef

$(eval $(call IMAGE_RULES,scenery,$(SCENERY),))
$(eval $(call IMAGE_RULES,sound,$(SOUND),))
$(eval $(call IMAGE_RULES,screens,$(SCREENS),))
$(eval $(call IMAGE_RULES,map,$(MAP),))
$(eval $(call IMAGE_RULES,main,$(MAIN),$(BUILD)/map.bin $(BUILD)/scenery.bin $(BUILD)/screens.bin $(BUILD)/sound.bin))

$(BUILD)/inc:
	mkdir -p $@

$(BUILD)/empty_banks.bin: | $(BUILD)/inc
	head -c 24576 /dev/zero | tr '\000' '\377' > $@

$(ROM): $(addprefix $(BUILD)/,$(addsuffix .bin,$(IMAGES))) $(BUILD)/empty_banks.bin
	cat $(addprefix $(BUILD)/,$(addsuffix .bin,$(IMAGES))) $(BUILD)/empty_banks.bin > $@

rom: $(ROM)

# The test that decides whether the sources are right: they have to give
# back the original cartridge, byte for byte.
verify: $(ROM)
	@echo "$(SHA)  $(ROM)" | sha256sum -c -

# ------------------------------------------------------------------ checks

# What the reassembly can NOT catch: bytes written as instructions that the
# game never executes, or code written as data. The bytes come out the same
# either way; only what the sources say about them changes. The
# whole-cartridge tracer (tools/bank_tracer.py) follows the code from the two
# entry points the hardware guarantees, keeping track of which bank is in
# each slot, and its result has to match the sources exactly.
sanity: $(ROM)
	@echo "=================================================================="
	@echo " every write to the mapper obeys the bank -> org rule"
	@echo "=================================================================="
	@python3 tools/recon.py $(ROM) | tail -1
	@echo "=================================================================="
	@echo " code and data in the sources match what the tracer finds"
	@echo "=================================================================="
	@python3 tools/check_code.py $(ROM) $(BUILD) $(SRC)

# The mark Konami hid at the end of bank 3. The discovery is by
# Manuel Pazos (@ManuelPazosMSX), not ours.
mark: $(ROM)
	@python3 tools/konami_mark.py $(ROM)

recon: $(ROM)
	@python3 tools/recon.py $(ROM)

# Puts in both READMEs the figures that are really in the tree. The tests
# compare both, so this is run after every round of comments.
figures: $(ROM)
	@python3 tools/figures.py

density:
	@python3 tools/density.py $(SRC)

# The sources carry no addresses. This writes build/listing/<image>.lst: every
# module of each image in link order, every line with its bank and address.
listing: $(ROM)
	@python3 tools/listing.py $(BUILD) $(SRC)

test: $(ROM)
	@echo "=================================================================="
	@echo " Tests"
	@echo "=================================================================="
	@python3 -m unittest discover -s tests -v

# The website images are NOT screenshots: tools/graphics.py runs in Python the
# decompressor at 0x49B9, the character loader at 0x42FC and the column
# builder at 0x46AE, and draws the screens and the twelve maps from the ROM.
images: $(ROM)
	@python3 tools/graphics.py

web: images
	@python3 tools/md2html.py docs en
	@python3 tools/md2html.py docs/es es
	@python3 tools/make_web.py docs/images docs/index.html en
	@python3 tools/make_web.py docs/images docs/es/index.html es
	@python3 tools/check_links.py docs

clean:
	rm -rf $(BUILD)

.PHONY: all rom verify sanity mark recon figures density listing test images web clean
