; ============================================================================
; Sound player - The sound streams
; ============================================================================
;
; The melodies and the effects, one label per sound, from 0x83C8 in bank 7 to
; 0xA3DE in bank 8.
;
; THIS MODULE CROSSES THE BANK BOUNDARY. Banks 7 and 8 are always mapped
; together (the interrupt does it at p00:402C-p00:4032 and the sound trigger at
; p00:49EF-p00:49FB), so for the player they are 16 KB in a row. The build
; links the whole image at 0x8000 and cuts it at 0xA000 afterwards; the rest of
; bank 8 is 0xFF filler generated by the linker (--fill 0FFh), not written here.
;
; The bytes of each stream are kept as they are: the addresses inside the 0xFE
; commands are still plain numbers.

	public empty_sound,sound_01,sound_02,sound_03,sound_04,sound_05,sound_06,sound_07
	public sound_08,sound_09,sound_10,sound_11,sound_12,sound_13,sound_14,sound_15
	public sound_16,sound_17,sound_18,sound_19,sound_20,sound_21,sound_22,sound_23
	public sound_24,sound_25,sound_26,sound_27,sound_28,sound_29,sound_30,sound_31
	public sound_32,sound_33,sound_34,sound_35,sound_36,sound_37,sound_38,sound_39
	public sound_40,sound_41,sound_42,sound_43,sound_44,sound_45,sound_46,sound_47
	public sound_48,sound_49,sound_50,sound_51,sound_52,sound_53,sound_54,sound_55
	public sound_56,sound_57,sound_58,sound_59,sound_60,sound_61,sound_62,sound_63
	public sound_64,sound_65,sound_66,sound_67,sound_68,sound_69,sound_70,sound_71
	public sound_72,sound_73,sound_74,sound_75,sound_76

; ----------------------------------------------------------------------
; DATA sound_data: The melodies and the effects, one after another, in the
;   order in which the table above names them: 0x83C8, 0x83F3, 0x8400, ...
;   0x9FBF. They continue in bank 8, which is mapped at the same time.
sound_01:
sound_02:
	defb 22h,01h,0C0h,50h,0C0h,54h,0C0h,58h,0C0h,60h,0B0h,54h,0B0h,58h,0B0h,60h
	defb 0C0h,50h,0C0h,54h,0C0h,58h,0C0h,60h,0B0h,54h,0B0h,58h,0B0h,60h,0A0h,58h
	defb 0A0h,60h,90h,58h,90h,60h,80h,60h,70h,60h,0FFh

sound_03:
	defb 2Ah,03h,00h,08h,0E0h,12h,0E0h,10h,0E0h,0Eh,0E0h,0Ch,0FFh

sound_04:
	defb 22h,01h,0F0h,40h,0F0h,58h,0F0h,78h,0F0h,0A0h,0F0h,08h,0A0h,18h,0A0h,38h
	defb 0A0h,60h,0A0h,08h,80h,20h,80h,48h,80h,20h,60h,48h,0FFh

sound_05:
	defb 22h,01h,0F0h,40h,0F0h,0C0h,0F1h,40h,0F1h,0C0h,0F2h,40h,0F2h,0C0h,0E0h,40h
	defb 0E1h,00h,0E1h,0C0h,0E2h,80h,0E3h,40h,0D0h,40h,0D1h,40h,0D2h,40h,0D3h,40h
	defb 0C0h,40h,0C1h,0C0h,0C3h,40h,0FFh

sound_06:
	defb 22h,01h,0F0h,20h,80h,60h,0F0h,20h,80h,60h,0C0h,20h,40h,60h,0FFh

sound_12:
	defb 23h,02h,1Fh,0A5h,50h,0B6h,50h,0C7h,50h,23h,04h,15h,0E8h,50h,00h,00h
	defb 23h,02h,1Fh,0C7h,50h,0D8h,50h,0E9h,50h,23h,04h,15h,0FAh,52h,00h,00h
	defb 23h,02h,1Fh,0C9h,50h,0DAh,00h,0EAh,50h,23h,04h,15h,0FBh,52h,0FFh

sound_07:
	defb 22h,01h,0F1h,0ACh,0F1h,0E1h,0F2h,3Ah,0F1h,3Fh,0F1h,67h,0F1h,0ABh,0F1h,0Fh
	defb 0F0h,0EFh,0F1h,1Eh,0F0h,0D5h,0F0h,6Ah,0F0h,65h,0F0h,6Ah,0F0h,65h,0F0h,0A9h
	defb 0F0h,8Fh,0F0h,54h,0F0h,54h,0F0h,54h,0F0h,0D6h,0F0h,0CAh,0F0h,0BEh,0F0h,0B4h
	defb 0F0h,0AAh,0E0h,6Bh,0E0h,35h,0E0h,6Bh,0FFh

sound_08:
	defb 22h,02h,0D0h,40h,0D0h,50h,0D0h,70h,0D0h,0A0h,0C0h,40h,0C0h,50h,0C0h,70h
	defb 0B0h,30h,0B0h,40h,0A0h,30h,0FFh

sound_09:
	defb 22h,01h,0E0h,60h,0E0h,80h,0E0h,0C0h,0E1h,00h,0E1h,40h,0E1h,80h,0E1h,40h
	defb 0E1h,00h,0E0h,0C0h,0E0h,80h,0E0h,60h,0C0h,80h,0C0h,0C0h,0C1h,00h,0C1h,40h
	defb 0C1h,80h,0C1h,40h,0C1h,00h,0C0h,0C0h,0C0h,80h,0C0h,60h,0FFh

sound_10:
	defb 22h,01h,0F0h,80h,0E1h,00h,0F1h,80h,0F2h,00h,0D1h,00h,0E2h,80h,0E3h,00h
	defb 0D1h,00h,0D3h,80h,0D4h,00h,0D1h,00h,0C4h,80h,0D1h,00h,0C5h,00h,0E1h,80h
	defb 0E1h,40h,0D1h,00h,0D0h,0C0h,0C0h,80h,0C0h,40h,0B0h,20h,0D1h,00h,0D0h,0C0h
	defb 0C0h,80h,0C0h,40h,0B0h,20h,0C0h,80h,0C0h,40h,0B0h,20h,0FFh

sound_11:
	defb 23h,01h,15h,0F0h,20h,0E1h,00h,0D1h,80h,0C2h,00h,23h,01h,1Fh,0F0h,25h
	defb 0F0h,1Ah,0F0h,15h,0E0h,10h,0E0h,2Ah,0D0h,20h,0D0h,10h,0C0h,0Ah,0C0h,25h
	defb 0B0h,1Ah,0B0h,15h,0A0h,10h,0A0h,2Ah,0A0h,20h,90h,10h,90h,0Ah,90h,25h
	defb 90h,1Ah,0FFh

sound_13:
	defb 22h,01h,0F0h,80h,0F1h,00h,0E1h,80h,0E2h,00h,0D2h,80h,0D3h,00h,0E1h,80h
	defb 0E1h,40h,0D1h,00h,80h,0C0h,80h,80h,80h,60h,0FFh

sound_14:
	defb 22h,01h,0F0h,20h,0F0h,0A0h,0F1h,10h,0F1h,70h,0E1h,0C0h,0E2h,00h,0E2h,30h
	defb 0D2h,50h,0D2h,60h,23h,02h,1Dh,0F2h,80h,0E3h,80h,0D4h,80h,23h,01h,1Fh
	defb 0F2h,80h,0D3h,80h,0B4h,80h,23h,06h,1Fh,0E3h,00h,0C3h,40h,0A3h,80h,83h
	defb 0C0h,74h,00h,64h,40h,54h,80h,44h,0C0h,0FFh

sound_18:
	defb 22h,01h,0F2h,00h,0F1h,0A0h,0F1h,40h,0F0h,0E0h,0F0h,80h,0F0h,60h,0F0h,40h
	defb 0F0h,20h,0E2h,00h,0E1h,0A0h,0E1h,40h,0E0h,0E0h,0E0h,80h,0E0h,60h,0E0h,40h
	defb 0E0h,20h,0D2h,00h,0D1h,0A0h,0D1h,40h,0D0h,0E0h,0D0h,80h,0D0h,60h,0D0h,40h
	defb 0D0h,20h,0C2h,00h,0C1h,0A0h,0C1h,40h,0C0h,0E0h,0C0h,80h,0C0h,60h,0C0h,40h
	defb 0C0h,20h,0B2h,00h,0B1h,0A0h,0B1h,40h,0B0h,0E0h,0B0h,80h,0B0h,60h,0B0h,40h
	defb 0B0h,20h,92h,00h,91h,0A0h,91h,40h,90h,0E0h,90h,80h,90h,60h,90h,40h
	defb 90h,20h,0FFh

sound_15:
	defb 22h,01h,0F0h,20h,0F0h,0A0h,0F1h,10h,0F1h,70h,0F1h,0C0h,0F2h,00h,0F2h,30h
	defb 0F2h,50h,0F2h,60h,0E0h,60h,0E0h,0A0h,0E1h,10h,0E1h,70h,0E1h,0C0h,0E2h,00h
	defb 0E2h,30h,0E2h,50h,0E2h,60h,0C0h,60h,0C0h,0A0h,0C1h,10h,0C1h,70h,0C1h,0C0h
	defb 0C2h,00h,0C2h,30h,0C2h,50h,0C2h,60h,0D0h,60h,0D0h,0A0h,0D1h,10h,0D1h,70h
	defb 0D1h,0C0h,0D2h,00h,0D2h,30h,0D2h,50h,0D2h,60h,0C0h,60h,0C0h,0A0h,0C1h,10h
	defb 0C1h,70h,0C1h,0C0h,0C2h,00h,0C2h,30h,0C2h,50h,0C2h,60h,0FFh

sound_16:
	defb 22h,01h,0D0h,0E2h,0E0h,0AAh,0F0h,8Fh,0F0h,86h,0F0h,8Fh,0F0h,86h,0F0h,8Fh
	defb 0F0h,86h,0F0h,8Fh,0E0h,86h,0E0h,8Fh,0D0h,86h,0D0h,8Fh,0E0h,86h,0E0h,8Fh
	defb 0F0h,71h,0F0h,55h,0F0h,47h,0F0h,42h,0F0h,47h,0F0h,42h,0E0h,47h,0E0h,42h
	defb 0E0h,47h,0D0h,42h,0D0h,47h,0D0h,42h,0C0h,47h,0C0h,42h,0C0h,47h,0C0h,42h
	defb 0B0h,47h,0B0h,42h,0FFh

sound_17:
	defb 22h,02h,0F0h,82h,0F0h,8Fh,0F0h,82h,0F0h,8Fh,0F0h,82h,0F0h,8Fh,22h,01h
	defb 0F0h,8Ch,0F0h,84h,0F0h,8Ch,0E0h,80h,0E0h,88h,0E0h,80h,0E0h,78h,0E0h,88h
	defb 0D0h,78h,0D0h,70h,0D0h,78h,0C0h,70h,0C0h,68h,0C0h,70h,0A0h,68h,0A0h,60h
	defb 0A0h,68h,90h,5Ch,0FFh

sound_19:
	defb 23h,01h,18h,0F1h,00h,0F2h,00h,0F3h,00h,0E4h,00h,0E5h,00h,0E6h,00h,0D7h
	defb 00h,0C8h,00h,23h,01h,1Fh,0F6h,00h,0F2h,80h,0F3h,00h,0E3h,80h,0E4h,00h
	defb 0E4h,80h,0D5h,00h,0D5h,80h,23h,06h,1Fh,0F3h,00h,0F3h,40h,0E3h,80h,0E3h
	defb 0C0h,0D4h,00h,0C4h,40h,0C4h,80h,0B4h,0C0h,0A5h,00h,95h,40h,85h,80h,75h
	defb 0C0h,66h,00h,0FFh

sound_20:
	defb 22h,05h,0F0h,54h,22h,02h,0F0h,90h,22h,05h,0F0h,54h,22h,02h,0F0h,90h
	defb 22h,05h,0F0h,54h,22h,02h,0F0h,90h,22h,05h,0E0h,54h,22h,02h,0E0h,90h
	defb 22h,05h,0D0h,54h,22h,02h,0D0h,90h,22h,05h,0C0h,54h,22h,02h,0C0h,90h
	defb 22h,05h,0B0h,54h,22h,02h,0B0h,90h,22h,05h,0A0h,54h,22h,02h,0A0h,90h
	defb 0FFh

sound_21:
	defb 22h,05h,0F0h,0DDh,0F0h,1Dh,0E0h,0DDh,0E0h,1Dh,0D0h,0DDh,0D0h,1Dh,0B0h,0DDh
	defb 0B0h,1Dh,90h,0DDh,90h,1Dh,70h,0DDh,70h,1Dh,60h,0DDh,60h,1Dh,0FFh

sound_22:
	defb 0D6h,0FCh,53h,0E3h,21h,21h,0E2h,21h,0E3h,20h,21h,21h,20h,0E1h,01h,01h
	defb 0E3h,21h,21h,0E2h,21h,0E3h,20h,21h,21h,20h,0FDh,43h,0E1h,00h,0E2h,0B0h
	defb 0E1h,01h,00h,0E3h,01h,01h,0FCh,53h,0E3h,0C0h,20h,21h,21h,20h,0FDh,43h
	defb 0E1h,00h,0E2h,0B0h,0E1h,01h,42h,32h,22h,32h,41h,51h,0FCh,53h,0E3h,41h
	defb 41h,0FCh,90h,0E1h,61h,0FCh,53h,0E3h,40h,41h,41h,40h,0FDh,53h,0E1h,60h
	defb 50h,61h,0C0h,62h,61h,0C2h,61h,60h,91h,91h,0C0h,62h,61h,0C2h,61h,60h
	defb 91h,90h,0C0h,0FCh,45h,0E3h,80h,0E2h,30h,60h,0A0h,0E1h,00h,30h,60h,30h
	defb 00h,0E2h,70h,60h,30h,0D4h,0E3h,80h,0E2h,30h,60h,0A0h,0E1h,00h,30h,0D6h
	defb 0E3h,70h,0E2h,20h,50h,90h,0B0h,0E1h,20h,50h,20h,0E2h,0B0h,70h,50h,20h
	defb 0D4h,0E3h,40h,0E2h,20h,50h,90h,0B0h,0E1h,20h,0D6h,0E3h,30h,0E2h,10h,40h
	defb 80h,0A0h,0E1h,10h,40h,10h,0E2h,0A0h,50h,40h,10h,0E3h,30h,0A0h,0E2h,10h
	defb 0E3h,20h,0FCh,62h,0E1h,08h,0FCh,74h,0E3h,01h,00h,31h,31h,0FCh,62h,0E1h
	defb 08h,0FCh,74h,0E3h,01h,00h,0E2h,61h,61h,0C0h,60h,61h,61h,50h,64h,60h
	defb 50h,30h,0FCh,66h,0Ch,0FCh,74h,31h,31h,0FEh,0FFh,0A2h,87h

sound_23:
	defb 0D6h,0FCh,53h,0E4h,21h,21h,0E3h,21h,0E4h,20h,21h,21h,20h,0E2h,21h,21h
	defb 0E4h,21h,21h,0E3h,21h,0E4h,20h,21h,21h,20h,0E2h,21h,21h,0E4h,21h,21h
	defb 0E2h,21h,0E4h,20h,21h,21h,20h,0E2h,21h,21h,0FDh,43h,0E3h,21h,20h,11h
	defb 10h,01h,00h,10h,11h,20h,20h,31h,0FCh,53h,0E4h,41h,41h,0E2h,41h,0E4h
	defb 40h,41h,41h,40h,0E2h,40h,30h,41h,0FDh,63h,0E4h,41h,41h,0E2h,41h,0E4h
	defb 40h,41h,41h,40h,71h,71h,41h,41h,0E2h,41h,0E4h,40h,41h,41h,40h,51h
	defb 70h,0FCh,28h,0E1h,0ACh,0A0h,0A1h,9Ch,90h,91h,8Ch,50h,52h,0E4h,21h,21h
	defb 0E3h,21h,0E4h,20h,21h,21h,20h,51h,51h,21h,21h,0E3h,21h,0E4h,20h,21h
	defb 21h,20h,0FDh,28h,81h,81h,0C0h,80h,81h,81h,70h,84h,80h,70h,60h,22h
	defb 80h,0E3h,01h,21h,01h,21h,00h,31h,31h,0FEh,0FFh,7Fh,88h

sound_24:
	defb 0D7h,0FCh,37h,0E1h,0C0h,20h,21h,0C0h,10h,11h,0C0h,20h,20h,20h,0E2h,91h
	defb 0E1h,11h,0C0h,20h,21h,0C0h,10h,11h,0C0h,20h,20h,20h,0E2h,91h,0E1h,11h
	defb 0C0h,20h,21h,0C0h,10h,11h,0C0h,20h,20h,20h,0E2h,91h,0E1h,11h,0C0h,20h
	defb 21h,0C0h,10h,11h,0C0h,20h,20h,20h,0E2h,91h,0E1h,11h,0C0h,0E2h,50h,51h
	defb 0A1h,80h,0A0h,0C0h,0E1h,11h,10h,31h,0C0h,0E2h,50h,51h,0A1h,80h,0A0h,0C0h
	defb 0E1h,11h,10h,0C0h,0E2h,50h,51h,0A1h,80h,0A0h,0C0h,0E1h,11h,10h,31h,0C0h
	defb 0E2h,50h,51h,0A1h,80h,0A0h,0C0h,0E1h,11h,10h,0E1h,0C0h,20h,21h,0C0h,10h
	defb 11h,0C0h,20h,20h,20h,0E2h,91h,0E1h,11h,0C0h,20h,21h,0C0h,10h,11h,0C0h
	defb 20h,20h,20h,0E2h,91h,0E1h,11h,0C0h,20h,21h,0C0h,11h,0E2h,90h,0E1h,0C0h
	defb 20h,21h,0C0h,11h,0E2h,90h,0D5h,0FCh,23h,0E1h,21h,11h,21h,11h,0E2h,91h
	defb 0E1h,11h,21h,11h,0FEh,0FFh,1Ch,89h

sound_25:
	defb 0D7h,0FDh,43h,0E4h,91h,0E3h,10h,20h,21h,11h,62h,10h,21h,0E4h,0B1h,91h
	defb 0E3h,10h,20h,21h,11h,62h,10h,21h,0E4h,0B1h,91h,0E3h,10h,20h,21h,11h
	defb 62h,10h,21h,0FEh,02h,0DCh,89h,0E4h,0B1h,0E3h,01h,50h,30h,81h,41h,51h
	defb 21h,01h,01h,50h,30h,81h,41h,51h,21h,01h,50h,30h,81h,41h,51h,21h
	defb 01h,01h,50h,30h,81h,41h,51h,21h,0E4h,91h,0E3h,10h,20h,21h,11h,62h
	defb 10h,21h,0E4h,0B1h,0E4h,91h,0E3h,10h,20h,21h,11h,62h,10h,21h,0E4h,0B1h
	defb 91h,0E3h,10h,20h,21h,11h,0E4h,91h,0E3h,10h,20h,21h,11h,0D5h,0E4h,91h
	defb 0E3h,11h,21h,11h,21h,11h,21h,11h,0FEh,0FFh,0C4h,89h

sound_26:
	defb 0D6h,0FDh,53h,0E1h,02h,01h,00h,01h,21h,21h,0E3h,71h,71h,0E1h,32h,32h
	defb 51h,51h,0E3h,71h,70h,71h,70h,0FDh,39h,0E1h,77h,50h,40h,00h,0E2h,74h
	defb 50h,40h,00h,0E3h,74h,0E2h,42h,72h,0E1h,01h,77h,50h,40h,00h,0E2h,74h
	defb 50h,40h,00h,0E3h,74h,0E2h,72h,0E1h,02h,41h,0E1h,77h,50h,40h,00h,0E2h
	defb 52h,20h,40h,0D4h,0FDh,45h,53h,43h,53h,73h,53h,73h,0D6h,0FDh,73h,80h
	defb 0A0h,0E1h,00h,20h,30h,20h,00h,0E2h,0A0h,80h,0A0h,80h,70h,50h,70h,50h
	defb 30h,0FDh,45h,22h,52h,0A2h,0E1h,32h,83h,0FDh,39h,77h,50h,40h,00h,0E2h
	defb 71h,70h,0E1h,01h,20h,31h,34h,30h,51h,54h,50h,71h,71h,50h,79h,0FEh
	defb 0FFh,40h,8Ah

sound_27:
	defb 0D6h,0FDh,28h,0E2h,92h,91h,90h,91h,0B1h,0B1h,0E4h,71h,71h,0E1h,02h,02h
	defb 21h,21h,0E4h,71h,70h,71h,70h,0FDh,42h,0E3h,01h,0E2h,01h,0E3h,01h,0E2h
	defb 01h,0FEh,04h,0DCh,8Ah,0E4h,0A1h,0E3h,0A1h,0E4h,0A1h,0E3h,0A1h,0FEh,04h,0E8h
	defb 8Ah,0E4h,91h,0E3h,91h,0E4h,91h,0E3h,91h,0FEh,02h,0F4h,8Ah,0E4h,21h,0E3h
	defb 21h,0E4h,21h,0E3h,21h,0E4h,41h,0E3h,41h,0E4h,41h,0E3h,41h,0E4h,51h,0E3h
	defb 51h,0E4h,51h,0E3h,51h,0FEh,02h,10h,8Bh,0E4h,71h,0E3h,71h,0E4h,71h,0E3h
	defb 71h,0FEh,02h,1Ch,8Bh,0E4h,01h,0E3h,01h,0E4h,01h,0E3h,01h,0FEh,02h,28h
	defb 8Bh,0E4h,31h,0E3h,31h,0E4h,31h,0E3h,30h,30h,0E4h,51h,0E3h,51h,0E4h,51h
	defb 0E3h,50h,50h,00h,01h,01h,01h,08h,0FEh,0FFh,0C3h,8Ah

sound_28:
	defb 0D5h,0FDh,55h,0E2h,31h,0A1h,31h,0A1h,0C1h,31h,0FCh,31h,0E1h,0A1h,0E0h,31h
	defb 0E1h,0A1h,0E0h,31h,0C1h,0E1h,0A1h,0FDh,55h,0E2h,21h,91h,21h,91h,0C1h,21h
	defb 0FCh,31h,0E1h,91h,0E0h,21h,0E1h,91h,0E0h,21h,0C1h,0E1h,91h,0FDh,55h,0E2h
	defb 31h,0A1h,31h,0A1h,0C1h,31h,0FCh,31h,0E1h,0A1h,0E0h,31h,0E1h,0A1h,0E0h,31h
	defb 0C1h,0E1h,0A1h,0FDh,55h,0E2h,61h,0E1h,11h,0E2h,61h,0E1h,53h,33h,13h,01h
	defb 11h,11h,0E2h,31h,0A1h,31h,0A1h,31h,0A1h,0FCh,31h,0E0h,31h,0A1h,31h,0A1h
	defb 31h,0A1h,0FDh,55h,0E2h,21h,91h,21h,91h,21h,91h,0FCh,31h,0E0h,21h,91h
	defb 21h,91h,21h,91h,0FDh,55h,0E2h,11h,81h,11h,81h,0C1h,0E1h,11h,0E2h,01h
	defb 61h,01h,61h,0C1h,0E1h,01h,0C1h,0E2h,0B1h,0B1h,0B1h,0B1h,0C1h,0A1h,0C1h,0B1h
	defb 0C3h,0E1h,05h,0E1h,31h,73h,6Dh,0FEh,0FFh,4Fh,8Bh

sound_29:
	defb 0D5h,0FCh,33h,0E3h,01h,61h,0A1h,01h,61h,0A1h,0FEh,02h,0EEh,8Bh,0E4h,0B1h
	defb 0E3h,51h,91h,0E4h,0B1h,0E3h,51h,91h,0FEh,02h,0F8h,8Bh,01h,61h,0A1h,01h
	defb 61h,0A1h,0FEh,02h,06h,8Ch,31h,0A1h,0E2h,11h,0E3h,31h,0A1h,0FEh,03h,12h
	defb 8Ch,0E2h,11h,0E3h,01h,61h,0A1h,01h,61h,0A1h,0FEh,02h,1Dh,8Ch,0E4h,0B1h
	defb 0E3h,51h,91h,0E4h,0B1h,0E3h,51h,91h,0FEh,02h,28h,8Ch,0E4h,81h,0E3h,41h
	defb 81h,0E4h,81h,0E3h,41h,81h,0E4h,71h,0E3h,31h,71h,0E4h,71h,0E3h,31h,73h
	defb 21h,21h,21h,23h,13h,21h,0C3h,3Bh,3Dh,0FEh,0FFh,0EAh,8Bh

sound_30:
	defb 0DAh,0FDh,43h,0E2h,40h,90h,40h,91h,40h,41h,40h,61h,70h,77h,40h,60h
	defb 70h,60h,40h,90h,40h,91h,42h,90h,0B1h,0E1h,07h,0E2h,0B0h,0E1h,00h,0E2h
	defb 0B0h,90h,70h,90h,0E1h,20h,0E2h,90h,0E1h,21h,0E2h,92h,0E1h,20h,00h,0E2h
	defb 0B0h,90h,0E1h,00h,50h,00h,51h,02h,50h,40h,20h,00h,46h,20h,70h,00h
	defb 50h,0E2h,0B0h,0E1h,45h,0FDh,89h,0E3h,0B0h,0E2h,40h,0E3h,0B0h,0E2h,20h,0E3h
	defb 0B0h,0E2h,40h,0FDh,43h,0E1h,00h,01h,02h,0C0h,31h,31h,20h,0E2h,01h,21h
	defb 31h,21h,01h,21h,0C0h,0B1h,0B1h,0E1h,20h,11h,20h,10h,0E2h,0B0h,90h,0E3h
	defb 0B1h,0E2h,11h,21h,11h,21h,11h,0C0h,0E1h,01h,02h,70h,70h,70h,70h,60h
	defb 70h,0E2h,01h,21h,31h,21h,30h,30h,51h,0E1h,94h,90h,64h,60h,33h,20h
	defb 10h,0FDh,76h,01h,0E2h,0B1h,0A1h,0FCh,33h,9Bh,0FEh,0FFh,57h,8Ch

sound_31:
	defb 0D5h,0FDh,32h,0E4h,91h,0E3h,41h,0E4h,91h,0E3h,41h,0E4h,91h,0E3h,41h,0FEh
	defb 02h,0FCh,8Ch,0E4h,91h,0E3h,41h,0E3h,01h,71h,01h,71h,01h,71h,0E3h,01h
	defb 71h,01h,0E4h,0B1h,0E3h,61h,0E4h,0B1h,0E4h,91h,0E3h,41h,0E4h,91h,0E3h,41h
	defb 0FEh,03h,1Dh,8Dh,01h,71h,01h,71h,01h,71h,0FEh,02h,29h,8Dh,21h,91h
	defb 21h,91h,21h,91h,0FEh,02h,33h,8Dh,0E3h,51h,0E2h,01h,0E3h,51h,0E2h,01h
	defb 0FEh,03h,3Dh,8Dh,0E3h,41h,0B1h,41h,0B1h,41h,0B1h,0FEh,02h,49h,8Dh,0E4h
	defb 0B1h,0E3h,41h,0E4h,0B1h,0E3h,21h,0E4h,0B1h,0E3h,41h,0E4h,0B1h,0E3h,41h,0E4h
	defb 0B1h,0E3h,21h,0E4h,0B1h,0E3h,41h,0E4h,51h,0E3h,01h,0E4h,51h,0E3h,31h,0E4h
	defb 51h,0E3h,51h,0FEh,02h,6Ch,8Dh,0E4h,51h,0E3h,01h,0E4h,71h,0E3h,21h,0E4h
	defb 81h,0E3h,31h,0E4h,71h,0E3h,21h,0E4h,81h,0E3h,31h,0E4h,71h,0E3h,21h,0E4h
	defb 41h,0B1h,41h,0E3h,21h,0E4h,41h,0E3h,41h,0FEh,02h,94h,8Dh,0E4h,41h,0B1h
	defb 61h,0E3h,11h,0E4h,71h,0E3h,21h,0E4h,61h,0E3h,11h,0E4h,71h,0E3h,21h,0E4h
	defb 61h,0E3h,11h,0E4h,51h,0E3h,01h,0E4h,51h,0E3h,31h,0E4h,51h,0E3h,51h,0E4h
	defb 51h,0FEh,02h,0BAh,8Dh,0E3h,01h,0E4h,71h,0E3h,21h,0E4h,81h,0E3h,31h,0E4h
	defb 71h,0E3h,21h,0E4h,81h,0E3h,31h,0E4h,0A1h,0E3h,51h,0E4h,91h,0E3h,41h,0E4h
	defb 91h,0E3h,71h,0E4h,91h,0E3h,91h,0E4h,61h,0E3h,11h,0E4h,61h,0E3h,41h,0E4h
	defb 61h,0E3h,61h,0E4h,31h,0A1h,31h,0E3h,11h,0E4h,31h,0E3h,31h,0E4h,01h,71h
	defb 01h,0A1h,01h,0E3h,01h,0E4h,91h,0E3h,41h,0E4h,91h,0E3h,71h,0E4h,91h,0E3h
	defb 91h,0FEh,02h,0Ah,8Eh,0FEh,0FFh,0F5h,8Ch

sound_32:
	defb 0D5h,0FDh,33h,0E1h,05h,0E2h,75h,0E1h,03h,0E2h,0A5h,75h,53h,0E1h,05h,0E2h
	defb 75h,40h,70h,0E1h,00h,40h,59h,43h,21h,05h,0E2h,75h,0E1h,03h,0E2h,0A5h
	defb 75h,51h,7Eh,30h,50h,7Ah,20h,40h,50h,70h,90h,0B0h,0E1h,05h,0E2h,75h
	defb 0E1h,03h,0E2h,0A5h,75h,53h,0E1h,05h,0E2h,75h,00h,40h,70h,0E1h,00h,2Ch
	defb 0E2h,0A0h,0E1h,00h,20h,35h,0E2h,0A5h,0A0h,0E1h,00h,20h,40h,55h,15h,10h
	defb 30h,51h,7Bh,00h,20h,40h,50h,7Bh,00h,20h,40h,50h,0D1h,0E1h,0ACh,9Ch
	defb 8Dh,7Ch,6Ch,5Dh,0D5h,0FDh,77h,40h,31h,20h,0FCh,33h,17h,0FEh,0FFh,1Eh
	defb 8Eh

sound_33:
	defb 0D5h,0FDh,31h,0E3h,01h,0E4h,0B1h,91h,71h,0E3h,01h,0E4h,0B1h,91h,71h,0A1h
	defb 91h,71h,51h,0A1h,91h,71h,51h,0E3h,01h,0E4h,0B1h,91h,71h,0E3h,01h,0E4h
	defb 0B1h,91h,71h,51h,41h,21h,01h,51h,41h,21h,01h,0E3h,01h,0E4h,0B1h,91h
	defb 71h,0E3h,01h,0E4h,0B1h,91h,71h,0A1h,91h,71h,51h,0A1h,91h,71h,51h,31h
	defb 21h,01h,0E5h,0A1h,0E4h,31h,21h,01h,0E5h,0A1h,0E4h,21h,01h,0E5h,0B1h,91h
	defb 0E4h,71h,51h,41h,21h,0E3h,01h,0E4h,0B1h,91h,71h,0E3h,01h,0E4h,0B1h,91h
	defb 71h,0A1h,91h,71h,51h,0A1h,91h,71h,51h,0E3h,01h,0E4h,0B1h,91h,71h,0E3h
	defb 01h,0E4h,0B1h,91h,71h,0A1h,91h,71h,51h,0A1h,81h,71h,51h,0E3h,31h,21h
	defb 01h,0E4h,0A1h,0E3h,31h,21h,01h,0E4h,0A1h,0E3h,11h,01h,0E4h,0A1h,81h,0E3h
	defb 11h,01h,0E4h,0A1h,81h,0E4h,71h,21h,71h,0E3h,21h,0E4h,71h,0E3h,21h,71h
	defb 21h,0E4h,71h,21h,71h,0E3h,21h,0E4h,71h,0E3h,21h,71h,21h,0D2h,0FDh,23h
	defb 0E4h,79h,79h,79h,79h,0D5h,70h,71h,70h,77h,0FEh,0FFh,8Fh,8Eh

sound_34:
	defb 0D4h,0FAh,23h,0E1h,01h,31h,0E2h,0B1h,0E1h,31h,0FBh,23h,0E2h,0A1h,0E1h,31h
	defb 0E2h,91h,0E1h,31h,0FCh,23h,01h,31h,0E2h,0B1h,0E1h,31h,0FDh,23h,0E2h,0A1h
	defb 0E1h,31h,0E2h,91h,0E1h,31h,0FBh,00h,70h,0FCh,00h,70h,0FDh,00h,70h,0FCh
	defb 00h,70h,0FDh,23h,0E0h,21h,0E1h,71h,0E0h,21h,0E1h,71h,0E0h,21h,0FDh,33h
	defb 0E1h,51h,61h,71h,81h,0FDh,42h,73h,0FDh,23h,0E0h,21h,0E1h,71h,0E0h,21h
	defb 0E1h,71h,0E0h,21h,0FDh,32h,0E1h,91h,91h,0FDh,23h,91h,0C1h,0FAh,00h,0E1h
	defb 00h,00h,0FBh,00h,00h,00h,0FCh,00h,00h,00h,0FDh,00h,00h,00h,00h,00h
	defb 00h,00h,0FCh,00h,00h,00h,0FBh,00h,00h,00h,0FAh,00h,00h,00h,0FDh,23h
	defb 0E2h,0A1h,71h,31h,0D8h,0FAh,00h,0E2h,50h,0FBh,00h,50h,50h,0FCh,00h,50h
	defb 50h,50h,50h,0FBh,00h,50h,0F9h,00h,50h,50h,0F8h,00h,50h,50h,0D4h,0FAh
	defb 00h,0E1h,00h,00h,0FBh,00h,00h,00h,0FCh,00h,00h,00h,0FDh,00h,00h,00h
	defb 00h,00h,00h,00h,0FCh,00h,00h,00h,0FBh,00h,00h,00h,0FAh,00h,00h,00h
	defb 0FDh,23h,0E2h,0A1h,71h,0A1h,0D8h,0F9h,00h,0E1h,00h,00h,0FAh,00h,00h,00h
	defb 0FBh,00h,00h,00h,00h,0FAh,00h,00h,0F8h,00h,00h,00h,0F7h,00h,00h,00h
	defb 0D4h,0FBh,00h,0E1h,20h,0FCh,00h,20h,0FDh,00h,20h,0FCh,00h,20h,0FDh,23h
	defb 71h,21h,71h,21h,71h,0FDh,33h,01h,01h,0FDh,23h,03h,0FDh,42h,23h,0FDh
	defb 23h,71h,21h,71h,21h,71h,0FDh,22h,93h,93h,0FBh,00h,70h,0FCh,00h,70h
	defb 0FDh,00h,70h,0FCh,00h,70h,0FDh,23h,0E0h,21h,0E1h,71h,0E0h,21h,0E1h,71h
	defb 0E0h,21h,0FDh,33h,0E1h,51h,51h,0FDh,23h,53h,0FDh,42h,73h,0FDh,23h,0E0h
	defb 21h,0E1h,71h,0E0h,21h,0E1h,71h,0E0h,21h,0FDh,22h,0E1h,93h,93h,0FAh,00h
	defb 00h,00h,0FBh,00h,00h,00h,0FCh,00h,00h,00h,0FDh,00h,00h,00h,00h,00h
	defb 00h,00h,0FCh,00h,00h,00h,0FBh,00h,00h,00h,0FAh,00h,00h,00h,0FDh,23h
	defb 0E2h,0A1h,71h,31h,0D8h,0FAh,00h,0E2h,50h,0FBh,00h,50h,50h,0FCh,00h,50h
	defb 50h,50h,50h,0FBh,00h,50h,0F9h,00h,50h,50h,0F8h,00h,50h,50h,0D4h,0FAh
	defb 00h,0E1h,00h,00h,0FBh,00h,00h,00h,0FCh,00h,00h,00h,0FDh,00h,00h,00h
	defb 00h,00h,00h,00h,0FCh,00h,00h,00h,0FBh,00h,00h,00h,0FAh,00h,00h,00h
	defb 0FDh,23h,0E2h,0A1h,71h,0A1h,0D8h,0F9h,00h,0E1h,00h,00h,0FAh,00h,00h,00h
	defb 0FBh,00h,00h,00h,00h,0FAh,00h,00h,0F8h,00h,00h,00h,0F7h,00h,00h,00h
	defb 0D4h,0FDh,33h,0E0h,23h,23h,23h,0FDh,34h,01h,01h,01h,0FDh,33h,23h,23h
	defb 23h,0FDh,23h,01h,01h,51h,0FDh,32h,21h,0FDh,44h,0E1h,71h,21h,0FDh,32h
	defb 0E0h,01h,0FDh,44h,0E1h,51h,01h,0FDh,32h,0E0h,21h,0FDh,44h,0E1h,71h,0FDh
	defb 32h,0E0h,01h,0FDh,44h,0E1h,51h,0FDh,32h,21h,0FDh,44h,0E2h,71h,0FDh,32h
	defb 0E1h,01h,0FDh,44h,0E2h,51h,0FDh,32h,0E1h,21h,0FDh,44h,71h,0FEh,0FFh,0AAh
	defb 8Fh

sound_35:
	defb 0D4h,0FAh,33h,0E3h,01h,01h,01h,01h,0FBh,33h,01h,01h,01h,01h,0FCh,33h
	defb 01h,01h,01h,01h,0FDh,33h,01h,01h,01h,01h,31h,31h,0A1h,0E2h,31h,0E3h
	defb 31h,31h,0A1h,11h,11h,11h,11h,31h,31h,0A1h,0E2h,31h,0E3h,31h,31h,0A1h
	defb 11h,11h,11h,0C1h,0FDh,33h,0E3h,01h,01h,31h,0E2h,01h,0E3h,01h,31h,01h
	defb 01h,31h,0E2h,01h,0E3h,01h,31h,11h,11h,51h,0E2h,11h,0E3h,11h,51h,11h
	defb 11h,51h,0E2h,11h,0E3h,11h,51h,01h,01h,31h,0E2h,01h,0E3h,01h,31h,01h
	defb 01h,31h,0E2h,01h,0E3h,01h,31h,0E3h,11h,11h,51h,0E2h,11h,0E3h,11h,51h
	defb 11h,11h,51h,0E2h,11h,0E3h,11h,51h,31h,31h,0A1h,0E2h,31h,0E3h,31h,31h
	defb 0A1h,11h,11h,0FDh,32h,13h,0FDh,33h,31h,31h,0A1h,0E2h,31h,0E3h,31h,31h
	defb 0A1h,0FDh,32h,13h,13h,0FDh,33h,0E3h,31h,31h,0A1h,0E2h,31h,0E3h,31h,31h
	defb 0A1h,11h,11h,0FDh,32h,13h,0FDh,33h,31h,31h,0A1h,0E2h,31h,0E3h,31h,31h
	defb 0A1h,0FDh,32h,13h,13h,0FDh,33h,0E3h,01h,01h,31h,0E2h,01h,0E3h,01h,31h
	defb 01h,01h,31h,0E2h,01h,0E3h,01h,31h,11h,11h,51h,0E2h,11h,0E3h,11h,51h
	defb 11h,11h,51h,0E2h,11h,0E3h,11h,51h,01h,01h,31h,0E2h,01h,0E3h,01h,31h
	defb 01h,01h,31h,0E2h,01h,0E3h,01h,31h,0E3h,11h,11h,51h,0E2h,11h,0E3h,11h
	defb 51h,11h,11h,51h,0E2h,11h,0E3h,11h,51h,31h,31h,0A1h,0E2h,31h,0E3h,31h
	defb 0A1h,11h,11h,81h,31h,31h,0A1h,0E2h,31h,0E3h,31h,0A1h,11h,11h,81h,31h
	defb 0FDh,44h,0A1h,0E2h,31h,0FDh,33h,0E3h,11h,0FDh,44h,81h,0E2h,11h,0FDh,33h
	defb 0E3h,31h,0FDh,44h,0A1h,0FDh,33h,11h,0FDh,44h,81h,0FDh,33h,31h,0FDh,44h
	defb 0A1h,0FDh,33h,11h,0FDh,44h,81h,0FDh,33h,31h,0FDh,44h,0A1h,0FEh,0FFh,92h
	defb 91h

sound_36:
	defb 0D3h,0F6h,04h,0E2h,01h,0E1h,01h,0F7h,04h,0E2h,01h,01h,0F8h,04h,0E1h,01h
	defb 0E2h,01h,0F9h,04h,01h,0E1h,01h,0FAh,04h,0E2h,01h,01h,0FBh,04h,0E1h,01h
	defb 0E2h,01h,0FCh,04h,0E1h,01h,0E2h,01h,0FDh,04h,01h,0E1h,01h,0F6h,04h,0E2h
	defb 81h,0E1h,81h,0F7h,04h,0E2h,81h,81h,0F8h,04h,0E1h,81h,0E2h,81h,0F9h,04h
	defb 81h,0E1h,81h,0FAh,04h,0E2h,81h,81h,0FBh,04h,0E1h,81h,0E2h,81h,0FCh,04h
	defb 0E1h,81h,0E2h,81h,0FDh,04h,81h,0E1h,81h,0F6h,03h,0E2h,51h,0E1h,51h,0F7h
	defb 03h,0E2h,51h,51h,0F8h,03h,0E1h,51h,0E2h,51h,0F9h,03h,51h,0E1h,51h,0FAh
	defb 03h,0E2h,51h,51h,0FBh,03h,0E1h,51h,0E2h,51h,0FCh,04h,0E1h,51h,0E2h,51h
	defb 0FDh,04h,51h,0E1h,51h,0F6h,03h,0E2h,71h,0E1h,71h,0F8h,03h,0E2h,71h,71h
	defb 0FAh,03h,0E1h,71h,0E2h,71h,0FCh,04h,71h,0E1h,71h,0FBh,03h,0E1h,71h,0E2h
	defb 71h,0E3h,71h,0E1h,71h,0E2h,71h,0E1h,71h,71h,0E0h,21h,0D3h,0FBh,02h,0E1h
	defb 01h,0E0h,01h,0E1h,01h,0E0h,01h,0E1h,01h,0A1h,01h,71h,0FEh,02h,4Bh,93h
	defb 0E2h,81h,0E0h,01h,0E2h,81h,0E0h,01h,0E2h,81h,0E1h,0A1h,0E2h,81h,0E1h,71h
	defb 0FEh,02h,5Fh,93h,0E2h,51h,0E0h,01h,0E2h,51h,0E0h,01h,0E2h,51h,0E1h,0A1h
	defb 0E2h,51h,0E1h,71h,0E2h,51h,0E1h,51h,0E2h,51h,0E1h,31h,0E2h,51h,0E1h,21h
	defb 0E2h,51h,0E1h,31h,0E2h,71h,0E1h,21h,0E2h,71h,0E1h,01h,0E2h,71h,0B1h,71h
	defb 0E1h,01h,0E2h,71h,0E1h,21h,0E2h,71h,0E1h,31h,0E2h,71h,0E1h,51h,0E2h,71h
	defb 0B1h,0FDh,30h,0E1h,03h,0E2h,71h,0E1h,23h,0E2h,71h,0E1h,33h,0E2h,71h,0E1h
	defb 53h,0E2h,71h,0FDh,32h,0E1h,33h,02h,0C0h,0FEh,03h,0B0h,93h,0FDh,22h,0E1h
	defb 05h,0E2h,71h,0E1h,23h,0E2h,71h,0E1h,33h,0E2h,71h,0E1h,53h,31h,21h,01h
	defb 21h,0FDh,31h,0E1h,01h,0C1h,0E0h,01h,0C1h,0E1h,01h,0A1h,01h,71h,0FEh,02h
	defb 0E0h,93h,0E2h,81h,0C1h,0E0h,01h,0C1h,0E2h,81h,0E1h,0A1h,0E2h,81h,0E1h,71h
	defb 0FEh,02h,0F1h,93h,0E2h,51h,0C1h,0E0h,01h,0C1h,0E2h,51h,0E1h,0A1h,0E2h,51h
	defb 0E1h,71h,0E2h,51h,0C1h,0E1h,51h,31h,0E2h,51h,0E1h,31h,21h,31h,0E2h,71h
	defb 0C1h,0E1h,21h,01h,0E2h,71h,0E1h,01h,0E2h,0B1h,0E1h,01h,0E2h,71h,0E1h,21h
	defb 0E2h,71h,0E1h,31h,0E2h,71h,0E1h,51h,0E2h,71h,0B1h,0FDh,0Fh,0E2h,01h,0C1h
	defb 0E1h,01h,0C1h,0E2h,0A1h,0C1h,71h,51h,0C1h,31h,0C1h,21h,0C1h,01h,0C1h,21h
	defb 0FEh,02h,3Ah,94h,01h,0C1h,0E1h,01h,0C1h,0E2h,0A1h,0C1h,71h,53h,0C1h,0E1h
	defb 51h,0C1h,31h,0C1h,01h,0C1h,0FDh,21h,73h,0E2h,71h,0E1h,53h,0E2h,71h,0E1h
	defb 33h,0E2h,71h,0E1h,23h,0E2h,71h,0E1h,01h,0E2h,71h,0E1h,21h,0E2h,71h,0FDh
	defb 30h,0E1h,03h,0E2h,71h,0E1h,23h,0E2h,71h,0E1h,33h,0E2h,71h,0E1h,53h,0E2h
	defb 71h,0FDh,32h,0E1h,33h,02h,0C0h,0FEh,02h,7Eh,94h,03h,0E2h,71h,0E1h,23h
	defb 0E2h,71h,0E1h,33h,0E2h,71h,0E1h,53h,0E2h,71h,0E1h,31h,0E2h,71h,0E1h,51h
	defb 0E2h,71h,0E1h,73h,0E2h,0B1h,0E1h,53h,0E2h,0B1h,0E1h,33h,0E2h,71h,0E1h,23h
	defb 0E2h,71h,0FBh,02h,91h,0E1h,91h,0E2h,0B1h,0E1h,0B1h,0FEh,0FFh,4Bh,93h,0FFh

sound_37:
	defb 0D3h,0FDh,14h,0E4h,01h,0FCh,14h,0E3h,01h,0FDh,14h,0E4h,01h,01h,0FCh,14h
	defb 0E3h,01h,0FDh,14h,0E4h,01h,01h,0FCh,14h,0E3h,01h,0FDh,14h,0E4h,01h,01h
	defb 0FCh,14h,0E3h,01h,0FDh,14h,0E4h,01h,0FCh,14h,0E3h,01h,0FDh,14h,0E4h,01h
	defb 01h,0FCh,14h,0E3h,01h,0FDh,14h,0E4h,81h,0FCh,0Fh,0E3h,81h,0FDh,14h,0E4h
	defb 81h,81h,0FCh,0Fh,0E3h,81h,0FDh,14h,0E4h,81h,81h,0FCh,0Fh,0E3h,81h,0FDh
	defb 14h,0E4h,81h,81h,0FCh,0Fh,0E3h,81h,0FDh,14h,0E4h,81h,0FCh,0Fh,0E3h,81h
	defb 0FDh,14h,0E4h,81h,81h,0FCh,0Fh,0E3h,81h,0FDh,14h,0E4h,51h,0FCh,16h,0E3h
	defb 51h,0FDh,14h,0E4h,51h,51h,0FCh,16h,0E3h,51h,0FDh,14h,0E4h,51h,51h,0FCh
	defb 16h,0E3h,51h,0FDh,14h,0E4h,51h,51h,0FCh,16h,0E3h,51h,0FDh,14h,0E4h,51h
	defb 0FCh,16h,0E3h,51h,0FDh,14h,0E4h,51h,51h,0FCh,16h,0E3h,51h,0FDh,14h,0E4h
	defb 71h,0FCh,0Fh,0E3h,71h,0FDh,14h,0E4h,71h,71h,0FCh,0Fh,0E3h,71h,0FDh,14h
	defb 0E4h,71h,71h,0FCh,0Fh,0E3h,71h,0FDh,14h,0E4h,71h,71h,0FCh,0Fh,0E3h,71h
	defb 0FDh,14h,0E4h,71h,0FCh,0Fh,0E3h,71h,0FDh,14h,0E4h,71h,71h,0FCh,0Fh,0E3h
	defb 71h,0FEh,0FFh,0CFh,94h,0FFh

sound_50:
	defb 23h,01h,18h,0F1h,00h,0F2h,00h,0F3h,00h,0E4h,00h,0E5h,00h,0E6h,00h,0D7h
	defb 00h,0D8h,00h,23h,01h,1Fh,0F6h,00h,0E2h,80h,0E3h,00h,0E3h,80h,0E4h,00h
	defb 0E4h,80h,0D5h,00h,0D5h,80h,23h,06h,1Fh,0F4h,60h,0F4h,60h,0F4h,60h,0F4h
	defb 60h,0E4h,60h,0E4h,60h,23h,08h,1Eh,0D4h,80h,0C4h,0C0h,0B5h,00h,0A5h,40h
	defb 95h,80h,85h,0C0h,76h,00h,66h,40h,56h,80h,0FFh

sound_51:
	defb 22h,01h,0F2h,00h,0F3h,00h,0F4h,00h,0E5h,00h,0E6h,00h,0E7h,00h,0D8h,00h
	defb 0D9h,00h,0F7h,00h,0E3h,80h,0E4h,00h,0E4h,80h,0E5h,00h,0E5h,80h,0D6h,00h
	defb 0D6h,80h,22h,06h,0F5h,60h,0E5h,60h,0D5h,60h,0C5h,60h,0B5h,60h,0B5h,60h
	defb 22h,08h,0B5h,80h,0A5h,80h,95h,80h,85h,80h,75h,80h,65h,80h,65h,80h
	defb 65h,80h,55h,80h,0FFh

sound_52:
	defb 22h,01h,0F0h,10h,0F0h,30h,0F0h,50h,0E1h,00h,0E2h,00h,0E3h,00h,0D4h,00h
	defb 0D5h,00h,0F5h,00h,0E0h,80h,0E1h,00h,0E1h,80h,0E2h,00h,0E2h,80h,0D3h,00h
	defb 0D3h,80h,0F0h,50h,0F0h,80h,0F0h,0C0h,22h,03h,00h,00h,22h,06h,0E3h,00h
	defb 0D3h,00h,0C3h,00h,0B3h,00h,0A3h,00h,22h,08h,0A3h,80h,0A3h,0C0h,94h,00h
	defb 84h,40h,74h,80h,64h,0C0h,65h,00h,55h,40h,45h,80h,0FFh

sound_38:
	defb 0D3h,0FCh,24h,0E1h,19h,0FCh,37h,27h,45h,0FCh,24h,29h,0FCh,37h,17h,25h
	defb 0D6h,0FCh,33h,9Bh,0D3h,0FCh,13h,0B3h,0FCh,88h,91h,73h,0FCh,35h,65h,0FCh
	defb 88h,41h,0FCh,66h,25h,0FCh,24h,19h,0FCh,66h,27h,0FCh,33h,0B5h,0FCh,88h
	defb 93h,0B1h,0E0h,13h,0FCh,45h,25h,0FCh,88h,41h,63h,0FCh,45h,75h,0FCh,88h
	defb 61h,23h,0FBh,24h,0E1h,0B5h,0FCh,88h,0E0h,21h,0FCh,45h,13h,0FCh,45h,27h
	defb 0FCh,24h,0E1h,0B3h,0FCh,45h,95h,0FCh,88h,71h,63h,0FCh,24h,21h,19h,0FCh
	defb 37h,27h,45h,0FCh,24h,29h,0FCh,37h,17h,25h,0D6h,0FCh,33h,9Bh,0D3h,0FCh
	defb 13h,0B3h,0FCh,88h,91h,73h,0FCh,35h,65h,0FCh,88h,41h,0FCh,66h,25h,0FCh
	defb 24h,19h,0FCh,66h,27h,0FCh,33h,0B5h,0FCh,88h,93h,0B1h,0E0h,13h,0FCh,45h
	defb 25h,0FCh,88h,41h,63h,0FCh,45h,75h,0FBh,88h,61h,23h,0FBh,24h,0E1h,0B5h
	defb 0FBh,88h,0E0h,21h,0FAh,45h,0E0h,13h,0FAh,45h,0E0h,2Bh,0FAh,24h,0E1h,99h
	defb 0C3h,0FAh,45h,0E0h,73h,0F9h,88h,0E0h,61h,23h,0F9h,45h,0E1h,0B5h,0F8h,88h
	defb 0E1h,91h,73h,0F7h,24h,0E1h,6Fh,0C9h,0FFh

sound_39:
	defb 0D3h,0FCh,24h,0E2h,99h,0FCh,37h,0B7h,0E1h,15h,0FCh,24h,0E2h,0B9h,0FCh,37h
	defb 97h,0B5h,0FCh,24h,0E1h,19h,0FCh,37h,27h,45h,0FCh,24h,29h,0FCh,37h,0E2h
	defb 0BDh,0FCh,24h,99h,0FCh,66h,0B7h,0FCh,33h,0E1h,25h,0FCh,88h,15h,93h,0FCh
	defb 45h,67h,0FCh,88h,0B3h,0FCh,45h,0B5h,0FCh,88h,91h,0FCh,45h,63h,0FCh,24h
	defb 25h,0FCh,88h,71h,0FCh,45h,43h,0FCh,24h,75h,0FCh,88h,61h,0FCh,24h,43h
	defb 0FCh,45h,65h,0FCh,88h,41h,23h,0FCh,24h,0E2h,91h,99h,0FCh,37h,0B7h,0E1h
	defb 15h,0FCh,24h,0E2h,0B9h,0FCh,37h,97h,0B5h,0FCh,24h,0E1h,19h,0FCh,37h,27h
	defb 45h,0FCh,24h,29h,0FCh,37h,0E2h,0BDh,0FCh,24h,99h,0FCh,66h,0B7h,0FCh,33h
	defb 0E1h,25h,0FCh,88h,15h,93h,0FCh,45h,67h,0FCh,88h,0B3h,0FCh,45h,0B5h,0FBh
	defb 88h,91h,0FBh,45h,63h,0FBh,24h,25h,0FBh,88h,71h,0FBh,45h,43h,0FAh,24h
	defb 75h,0FAh,88h,61h,0FAh,45h,43h,0FAh,24h,65h,0FAh,88h,41h,0F9h,45h,23h
	defb 0C1h,0F9h,24h,0B3h,0F9h,88h,91h,63h,0FBh,45h,25h,0F8h,88h,11h,0E2h,93h
	defb 0F7h,24h,0E1h,2Fh,0C9h,0FFh

sound_40:
	defb 0D3h,0FCh,44h,0E3h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h
	defb 73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h
	defb 0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh
	defb 55h,21h,0FCh,44h,63h,0FCh,55h,11h,0FCh,44h,63h,0FCh,55h,11h,0FCh,44h
	defb 63h,0FCh,55h,11h,0FCh,44h,63h,0FCh,55h,11h,0FCh,44h,0E4h,0B5h,0FCh,55h
	defb 0E3h,13h,0FCh,44h,25h,0FCh,55h,41h,0FCh,44h,65h,73h,0FCh,55h,21h,0FCh
	defb 44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h
	defb 21h,0FCh,44h,65h,0FCh,55h,13h,0FCh,44h,0E4h,0B5h,0FCh,55h,0E3h,11h,23h
	defb 0FCh,44h,45h,0FCh,55h,61h,73h,0FCh,44h,95h,0FCh,55h,41h,0E4h,93h,0FCh
	defb 44h,0E3h,27h,73h,25h,41h,0FCh,55h,65h,0FCh,44h,0E3h,73h,0FCh,55h,21h
	defb 0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh
	defb 55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h
	defb 73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,63h,0FCh,55h,11h
	defb 0FCh,44h,63h,0FCh,55h,11h,0FCh,44h,63h,0FCh,55h,11h,0FCh,44h,63h,0FCh
	defb 55h,11h,0FCh,44h,0E4h,0B5h,0FCh,55h,0E3h,13h,0FCh,44h,25h,0FCh,55h,41h
	defb 0FCh,44h,65h,73h,0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,73h
	defb 0FCh,55h,21h,0FCh,44h,73h,0FCh,55h,21h,0FCh,44h,65h,0FCh,55h,13h,0FCh
	defb 44h,0E4h,0B5h,0FCh,55h,0E3h,11h,23h,0FCh,44h,45h,0FBh,55h,61h,73h,0FBh
	defb 44h,95h,0FBh,55h,41h,0E4h,93h,0FAh,44h,0E3h,27h,0FAh,55h,73h,0FAh,44h
	defb 25h,0FAh,44h,41h,0F9h,44h,65h,43h,0F9h,55h,61h,0F9h,44h,73h,0F9h,44h
	defb 95h,0F9h,55h,41h,0F9h,44h,0E4h,93h,0F9h,24h,0E3h,2Fh,0C9h,0FFh

sound_41:
	defb 0D5h,0FCh,24h,0E2h,93h,0E1h,41h,23h,01h,0E2h,0B1h,0E1h,03h,0E2h,0B1h,91h
	defb 0B3h,91h,73h,91h,91h,0E1h,41h,23h,7Fh,0C5h,0E2h,41h,91h,0E1h,41h,23h
	defb 01h,0E2h,0B3h,0E1h,01h,0E2h,0B1h,91h,0B1h,91h,75h,93h,0E1h,41h,21h,21h
	defb 0FAh,00h,7Fh,0FAh,0Fh,74h,0C0h,0FEh,0FFh,5Fh,99h

sound_42:
	defb 0D5h,0FBh,44h,0E1h,91h,91h,0E0h,91h,0E1h,91h,0FEh,0FFh,9Ah,99h

sound_43:
	defb 0D5h,0FCh,34h,0E3h,93h,91h,43h,41h,43h,51h,41h,21h,73h,81h,0B3h,93h
	defb 91h,41h,41h,41h,53h,51h,41h,21h,73h,71h,83h,93h,91h,43h,41h,43h
	defb 51h,41h,21h,0B1h,0B1h,71h,0B3h,53h,51h,03h,01h,53h,41h,41h,41h,0E3h
	defb 0B3h,41h,0E3h,42h,40h,0FEh,0FFh,0A8h,99h

sound_44:
	defb 0D1h,0FBh,33h,0E1h,0C0h,0D4h,41h,0E2h,0C1h,0E1h,41h,63h,0B3h,63h,43h,0E2h
	defb 0B1h,0E1h,41h,0E2h,0C1h,0E1h,41h,61h,41h,0E2h,0B1h,0E1h,41h,63h,0B3h,63h
	defb 43h,0E2h,0B1h,0E1h,41h,0E2h,0B1h,0E1h,41h,61h,0FEh,03h,0F9h,99h,0D8h,0FCh
	defb 33h,0E2h,80h,60h,80h,0A1h,0B1h,0A1h,81h,60h,80h,60h,80h,0C0h,80h,60h
	defb 80h,0A1h,0B1h,0A1h,81h,60h,80h,60h,80h,0C0h,60h,40h,60h,81h,91h,81h
	defb 61h,80h,60h,4Ah,10h,30h,40h,61h,40h,30h,10h,80h,60h,80h,0A1h,0B1h
	defb 0A1h,81h,60h,80h,60h,80h,0C0h,0FEh,02h,3Ch,9Ah,60h,40h,60h,81h,91h
	defb 82h,61h,80h,44h,60h,40h,24h,40h,20h,00h,00h,40h,60h,81h,60h,80h
	defb 0A1h,0B1h,0A1h,81h,60h,80h,60h,80h,0C0h,80h,60h,80h,0A1h,0B1h,0A1h,81h
	defb 60h,80h,60h,80h,0C0h,0FEh,0FFh,2Bh,9Ah

sound_45:
	defb 0D8h,0FDh,2Ch,0E2h,0BDh,0B1h,9Dh,91h,7Dh,71h,9Fh,0FCh,24h,0E3h,0B0h,0B0h
	defb 0E2h,40h,40h,0E3h,0B0h,0B0h,0E2h,40h,40h,0FEh,07h,8Dh,9Ah,0E3h,90h,90h
	defb 0E2h,20h,20h,0FEh,03h,97h,9Ah,0E3h,40h,40h,90h,90h,40h,40h,90h,90h
	defb 0FEh,04h,0A6h,9Ah,0E3h,0B0h,0B0h,0E2h,40h,40h,0FEh,08h,0AEh,9Ah,0E3h,90h
	defb 90h,0E2h,20h,20h,0FEh,03h,0B8h,9Ah,0E3h,70h,70h,0E2h,00h,00h,0E3h,70h
	defb 70h,0E2h,00h,00h,0E3h,50h,50h,0A0h,0A0h,0E3h,50h,50h,0A0h,0A0h,30h,30h
	defb 80h,80h,0FEh,0FFh,85h,9Ah

sound_46:
	defb 0D4h,0FCh,44h,0E0h,41h,0E1h,0B1h,0E0h,41h,63h,0B3h,63h,43h,0E1h,0B1h,0E0h
	defb 41h,0E1h,0B1h,0E0h,41h,61h,41h,0E1h,0B1h,0E0h,41h,63h,0B3h,63h,43h,0E1h
	defb 0B1h,0E0h,41h,0E1h,0B1h,0E0h,41h,61h,0FEh,02h,0F6h,9Ah,41h,0E1h,0B1h,0E0h
	defb 41h,63h,0B3h,63h,43h,0E1h,0B1h,0E0h,41h,0E1h,0B1h,0E0h,41h,61h,0FFh

sound_47:
	defb 0D6h,0FCh,25h,0E2h,13h,12h,60h,0B1h,0A3h,61h,0E1h,12h,0E2h,40h,45h,10h
	defb 20h,40h,90h,0B0h,0E1h,10h,0E2h,62h,32h,63h,0B1h,30h,50h,60h,80h,91h
	defb 60h,21h,91h,60h,0B1h,80h,41h,80h,0B1h,0E2h,13h,12h,60h,0B1h,0A3h,61h
	defb 0E1h,12h,0E2h,40h,45h,10h,20h,40h,90h,0B0h,0E1h,10h,31h,0E2h,60h,62h
	defb 0B1h,0E1h,11h,33h,0E2h,0B1h,82h,0E1h,1Bh,0C0h,0FCh,24h,0E2h,92h,62h,95h
	defb 60h,80h,91h,82h,42h,19h,0FCh,36h,30h,40h,60h,0B2h,61h,50h,60h,80h
	defb 0E1h,12h,0E2h,81h,60h,80h,90h,0E1h,22h,0E2h,91h,80h,90h,0B0h,0FBh,14h
	defb 0E1h,42h,0DCh,0FCh,14h,68h,0FEh,0FFh,1Fh,9Bh

sound_48:
	defb 0D6h,0FCh,26h,0E4h,61h,0E3h,60h,60h,0E4h,61h,0E3h,60h,60h,0FEh,03h,0A1h
	defb 9Bh,0E4h,91h,0E3h,90h,90h,0FEh,04h,0AAh,9Bh,0E4h,0B1h,0E3h,0B0h,0B0h,0FEh
	defb 04h,0B3h,9Bh,0E3h,21h,0E2h,20h,0C0h,0E3h,21h,0E2h,20h,20h,0E3h,41h,0E2h
	defb 40h,0C0h,0E3h,41h,0E2h,40h,40h,0E4h,61h,0E3h,60h,60h,0FEh,04h,0D0h,9Bh
	defb 0E4h,91h,0E3h,90h,90h,0FEh,04h,0D9h,9Bh,0E4h,0B1h,0E3h,0B0h,0B0h,0FEh,04h
	defb 0E2h,9Bh,0FBh,26h,0E3h,11h,0E2h,10h,10h,0FEh,04h,0EDh,9Bh,0FCh,23h,0E3h
	defb 20h,0E2h,20h,0E3h,90h,0E2h,20h,0E3h,20h,0E2h,20h,0E3h,90h,0E2h,20h,0FEh
	defb 03h,00h,9Ch,0E4h,90h,0E3h,90h,40h,90h,0FEh,04h,0Ch,9Ch,0E4h,0B0h,0E3h
	defb 0B0h,60h,0B0h,0E4h,0B0h,0E3h,0B0h,60h,0B0h,0E3h,10h,0E2h,10h,0E3h,80h,0E2h
	defb 10h,0FEh,02h,22h,9Ch,0E3h,20h,0E2h,20h,0E3h,90h,0E2h,20h,0FEh,02h,2Eh
	defb 9Ch,0E3h,40h,0E2h,40h,0E3h,0B0h,0E2h,40h,0FEh,02h,3Ah,9Ch,0E3h,61h,0E2h
	defb 60h,60h,0FEh,04h,46h,9Ch,0FEh,0FFh,99h,9Bh

sound_49:
	defb 0D6h,0FAh,11h,0E0h,60h,50h,30h,10h,0E1h,0B0h,0E0h,10h,30h,50h,60h,50h
	defb 30h,10h,0E1h,0B0h,0E0h,10h,30h,50h,60h,40h,20h,10h,0E1h,0B0h,0E0h,10h
	defb 20h,40h,0FEh,02h,6Bh,9Ch,60h,50h,30h,10h,0E1h,0B0h,0E0h,10h,30h,50h
	defb 0FEh,02h,79h,9Ch,60h,40h,20h,10h,0E1h,0B0h,0E0h,10h,20h,40h,60h,80h
	defb 90h,80h,60h,40h,20h,40h,0F9h,11h,60h,50h,0F8h,11h,30h,10h,0F7h,11h
	defb 0E1h,0B0h,0E0h,10h,0F6h,11h,30h,50h,0FFh

sound_53:
	defb 0D6h,0FCh,22h,0E3h,00h,10h,20h,30h,40h,50h,60h,70h,80h,90h,0A0h,0B0h
	defb 0E2h,00h,0FBh,12h,0E2h,30h,0E1h,30h,0E2h,0A0h,0E1h,00h,0FEh,02h,0C0h,9Ch
	defb 0E2h,70h,0E1h,30h,0E2h,0A0h,0E1h,00h,0E2h,50h,0E1h,30h,0E2h,0A0h,0E1h,00h
	defb 0E2h,30h,0E1h,30h,0E2h,0A0h,0E1h,00h,0E2h,50h,0E1h,30h,0E2h,0A0h,0E1h,00h
	defb 0E2h,70h,0E1h,30h,0E2h,0A0h,0E1h,00h,0E2h,50h,0E1h,30h,0E2h,0A0h,0E1h,00h
	defb 0FBh,02h,70h,70h,50h,70h,70h,70h,50h,0FEh,03h,01h,9Dh,70h,0A0h,0A0h
	defb 80h,0A0h,0A0h,0A0h,80h,0A0h,0FEh,02h,0Ah,9Dh,0E2h,30h,0E1h,30h,0E2h,0A0h
	defb 0E1h,00h,0E2h,50h,0E1h,30h,0E2h,0A0h,0E1h,00h,0FEh,0FFh,0CCh,9Ch

sound_54:
	defb 0D6h,0FAh,00h,0E2h,00h,10h,20h,30h,40h,50h,60h,70h,80h,90h,0A0h,0B0h
	defb 0E1h,00h,0FDh,35h,0E3h,31h,30h,30h,0FEh,10h,3Fh,9Dh,0FEh,0FFh,3Ch,9Dh

sound_55:
	defb 0D6h,0FCh,11h,0E1h,00h,10h,20h,30h,40h,50h,60h,70h,80h,90h,0A0h,0B0h
	defb 0E0h,00h,0FFh

sound_56:
	defb 22h,04h,0D0h,20h,0D0h,10h,0D0h,24h,0D0h,12h,0D0h,28h,0D0h,14h,0D0h,2Ch
	defb 0D0h,16h,0D0h,30h,0D0h,18h,0D0h,34h,0D0h,1Ah,0D0h,38h,0D0h,1Ch,0FEh,0Ah
	defb 5Dh,9Dh,0FFh

sound_57:
	defb 22h,04h,0D0h,10h,0D0h,08h,0D0h,12h,0D0h,09h,0D0h,14h,0D0h,0Ah,0D0h,16h
	defb 0D0h,0Bh,0D0h,18h,0D0h,0Ch,0D0h,1Ah,0D0h,0Dh,0D0h,1Ch,0D0h,0Eh,0FEh,0Ah
	defb 80h,9Dh,0FFh

sound_58:
	defb 22h,0Eh,0D0h,60h,0C0h,5Eh,0B0h,5Ch,0A0h,5Ah,90h,58h,0FEh,08h,0A3h,9Dh
	defb 0FFh

sound_59:
	defb 22h,01h,0F0h,20h,0F0h,0A0h,0F1h,10h,0F1h,70h,0D1h,0C0h,0D2h,00h,0D2h,30h
	defb 0D2h,50h,0D2h,60h,0E0h,60h,0E0h,0A0h,0E1h,10h,0E1h,70h,0E1h,0C0h,22h,02h
	defb 0F2h,00h,0F2h,30h,0F2h,50h,0F2h,60h,0E0h,60h,0E0h,0A0h,0E1h,10h,0E1h,70h
	defb 0E1h,0C0h,0D2h,00h,0D2h,30h,0D2h,50h,0D0h,60h,0D0h,0A0h,0B1h,10h,0B1h,70h
	defb 0B1h,0C0h,0B2h,00h,0B2h,30h,0A0h,60h,0A0h,0A0h,0A1h,10h,0A1h,70h,0A1h,0C0h
	defb 92h,00h,90h,60h,90h,0A0h,91h,10h,91h,70h,81h,0C0h,80h,60h,80h,0A0h
	defb 81h,10h,81h,70h,70h,60h,70h,0A0h,71h,10h,0FFh

sound_60:
	defb 22h,01h,0F0h,10h,0F0h,50h,0F0h,90h,0F0h,0B8h,0F0h,0E0h,0F1h,00h,0F1h,18h
	defb 0F1h,28h,0F1h,30h,0D0h,30h,0D0h,50h,0D0h,90h,0D0h,0B8h,0D0h,0E0h,22h,02h
	defb 0F1h,00h,0F1h,18h,0F1h,28h,0F1h,30h,0F0h,30h,0E0h,50h,0E0h,90h,0E0h,0B8h
	defb 0E0h,0E0h,0E1h,00h,0D1h,18h,0D1h,28h,0D0h,30h,0D0h,50h,0D0h,90h,0B0h,0B8h
	defb 0B0h,0E0h,0B1h,00h,0B1h,18h,0A0h,30h,0A0h,50h,0A0h,90h,0A0h,0B8h,0A0h,0E0h
	defb 91h,00h,90h,30h,90h,50h,90h,90h,90h,0B8h,80h,0E0h,80h,30h,80h,50h
	defb 80h,90h,80h,0B8h,70h,30h,70h,50h,70h,90h,0FFh

sound_61:
	defb 22h,01h,0F0h,40h,0F1h,40h,0F2h,20h,0F2h,0E0h,0D3h,80h,0D4h,00h,0D4h,60h
	defb 0D4h,0A0h,0D4h,0C0h,0E0h,0C0h,0E1h,40h,0E2h,20h,0E2h,0E0h,0E3h,80h,22h,02h
	defb 0F4h,00h,0F4h,60h,0F4h,0A0h,0F4h,0C0h,0F0h,0C0h,0E1h,40h,0E2h,20h,0E2h,0E0h
	defb 0E3h,80h,0E4h,00h,0D4h,60h,0D4h,0A0h,0D0h,0C0h,0D1h,40h,0D2h,20h,0B2h,0E0h
	defb 0B3h,80h,0B4h,00h,0B4h,60h,0A0h,0C0h,0A1h,40h,0A2h,20h,0A2h,0E0h,0A3h,80h
	defb 94h,00h,90h,0C0h,91h,40h,92h,20h,92h,0E0h,83h,80h,80h,0C0h,81h,40h
	defb 82h,20h,82h,0E0h,70h,0C0h,71h,40h,72h,20h,0FFh

sound_62:
	defb 22h,01h,0F1h,00h,0F0h,80h,0FEh,20h,0F7h,9Eh,0E1h,00h,0E0h,80h,0FEh,1Ch
	defb 0FFh,9Eh,0D1h,00h,0D0h,80h,0FEh,18h,07h,9Fh,0C1h,00h,0C0h,80h,0FEh,14h
	defb 0Fh,9Fh,0B1h,00h,0B0h,80h,0FEh,10h,17h,9Fh,0A1h,00h,0A0h,80h,0FEh,0Ch
	defb 1Fh,9Fh,91h,00h,90h,80h,0FEh,08h,27h,9Fh,81h,00h,80h,80h,0FEh,04h
	defb 2Fh,9Fh,0FFh

sound_63:
	defb 22h,01h,0F0h,80h,0F0h,40h,0FEh,20h,3Ah,9Fh,0E0h,80h,0E0h,40h,0FEh,1Ch
	defb 42h,9Fh,0D0h,80h,0D0h,40h,0FEh,18h,4Ah,9Fh,0C0h,80h,0C0h,40h,0FEh,14h
	defb 52h,9Fh,0B0h,80h,0B0h,40h,0FEh,10h,5Ah,9Fh,0A0h,80h,0A0h,40h,0FEh,0Ch
	defb 62h,9Fh,90h,80h,90h,40h,0FEh,08h,6Ah,9Fh,80h,80h,80h,40h,0FEh,04h
	defb 72h,9Fh,0FFh

sound_64:
	defb 21h,01h,10h,0F0h,00h,0F0h,00h,0FEh,20h,7Eh,9Fh,0E0h,00h,0E0h,00h,0FEh
	defb 1Ch,86h,9Fh,0D0h,00h,0D0h,00h,0FEh,18h,8Eh,9Fh,0C0h,00h,0C0h,00h,0FEh
	defb 14h,96h,9Fh,0B0h,00h,0B0h,00h,0FEh,10h,9Eh,9Fh,0A0h,00h,0A0h,00h,0FEh
	defb 0Ch,0A6h,9Fh,90h,00h,90h,00h,0FEh,08h,0AEh,9Fh,80h,00h,80h,00h,0FEh
	defb 04h,0B6h,9Fh,0FFh

sound_65:
	defb 21h,01h,1Fh,0F0h,00h,01h,1Eh,0F0h,00h,1Dh,0F0h,00h,1Ch,0F0h,00h,1Bh
	defb 0F0h,00h,1Ah,0F0h,00h,19h,0F0h,00h,18h,0F0h,00h,21h,05h,17h,0F0h,00h
	defb 16h,0F0h,00h,21h,01h,1Fh,0F0h,00h,1Eh,0F0h,00h,1Dh,0F0h,00h,1Ch,0F0h
	defb 00h,1Bh,0F0h,00h,1Ah,0F0h,00h,19h,0F0h,00h,18h,0F0h,00h,21h,05h,17h
	defb 0E0h

; ---- bank 8 starts here: the build cuts the image at 0xA000 ----

	defb 00h,16h,0F0h,00h,1Fh,0F0h,00h,1Eh,0F0h,00h,1Dh,0F0h,00h,1Ch,0F0h,00h
	defb 1Bh,0F0h,00h,1Ah,0E0h,00h,19h,0D0h,00h,18h,0C0h,00h,17h,0B0h,00h,16h
	defb 0A0h,00h,15h,90h,00h,14h,80h,00h,13h,70h,00h,12h,70h,00h,11h,60h
	defb 00h,60h,00h,0FFh

sound_66:
	defb 22h,28h,00h,00h,22h,05h,0F8h,0EEh,22h,0Ah,0E8h,0EEh,22h,05h,0D8h,0EEh
	defb 22h,0Ah,0B9h,0EEh,22h,05h,0A9h,0EEh,22h,0Ah,99h,0E9h,22h,05h,79h,0EEh
	defb 22h,05h,99h,0EEh,22h,05h,49h,0EEh,0FFh

sound_67:
	defb 22h,28h,00h,00h,22h,05h,0E0h,18h,22h,0Ah,0E0h,18h,22h,05h,0E0h,18h
	defb 22h,0Ah,0E0h,18h,22h,05h,0E0h,18h,22h,0Ch,0E0h,18h,22h,02h,0D0h,18h
	defb 0D0h,18h,22h,01h,0C0h,18h,22h,02h,0C0h,18h,0C0h,18h,0C0h,18h,0B0h,18h
	defb 0B0h,18h,22h,02h,0A0h,18h,0A0h,18h,22h,01h,0A0h,18h,0FFh

sound_68:
	defb 22h,06h,68h,0EEh,78h,0EEh,22h,07h,88h,0EEh,98h,0EEh,22h,08h,0A8h,0EEh
	defb 0B8h,0EEh,22h,09h,0C8h,0EEh,0D8h,0EEh,22h,0Ah,0E8h,0EEh,22h,38h,0D8h,0EEh
	defb 22h,0Ch,0C8h,0EEh,0FFh,22h,01h,0C1h,40h,0C0h,0A0h,0FEh,0Ch,0C1h,0A0h,0D1h
	defb 40h,0D0h,0A0h,0FEh,10h,0C9h,0A0h,0F1h,40h,0F0h,0A0h,0FEh,1Ch,0D1h,0A0h,0D1h
	defb 40h,0D0h,0A0h,0FEh,18h,0D9h,0A0h,0B1h,40h,0B0h,0A0h,0FEh,10h,0E1h,0A0h,91h
	defb 40h,90h,0A0h,0FEh,08h,0E9h,0A0h,71h,40h,70h,0A0h,0FEh,04h,0F1h,0A0h,0FFh

sound_69:
	defb 22h,06h,70h,20h,80h,20h,22h,07h,90h,20h,0A0h,20h,22h,08h,0B0h,20h
	defb 0C0h,20h,22h,09h,0D0h,20h,0E0h,20h,22h,0Ah,0F0h,20h,22h,38h,0F0h,20h
	defb 22h,0Ch,0D0h,20h,0FFh,22h,01h,0C0h,0A0h,0C0h,50h,0FEh,0Ch,21h,0A1h,0D0h
	defb 0A0h,0D0h,50h,0FEh,10h,29h,0A1h,0F0h,0A0h,0F0h,50h,0FEh,1Ch,31h,0A1h,0D0h
	defb 0A0h,0D0h,50h,0FEh,18h,39h,0A1h,0B0h,0A0h,0B0h,50h,0FEh,10h,41h,0A1h,90h
	defb 0A0h,90h,50h,0FEh,08h,49h,0A1h,70h,0A0h,70h,50h,0FEh,04h,51h,0A1h,0FFh

sound_70:
	defb 21h,06h,11h,70h,00h,12h,80h,00h,21h,07h,13h,90h,00h,14h,0A0h,00h
	defb 21h,08h,16h,0B0h,00h,18h,0C0h,00h,21h,09h,1Ah,0D0h,00h,1Ch,0E0h,00h
	defb 21h,0Ah,1Dh,0F0h,00h,21h,38h,1Fh,0F0h,00h,21h,0Ch,1Fh,0D0h,00h,0FFh
	defb 21h,01h,10h,0C0h,00h,0C0h,00h,0FEh,0Ch,8Dh,0A1h,0D0h,00h,0D0h,00h,0FEh
	defb 10h,95h,0A1h,0F0h,00h,0F0h,00h,0FEh,1Ch,9Dh,0A1h,0D0h,00h,0D0h,00h,0FEh
	defb 18h,0A5h,0A1h,0B0h,00h,0B0h,00h,0FEh,10h,0ADh,0A1h,90h,00h,90h,00h,0FEh
	defb 08h,0B5h,0A1h,70h,00h,70h,00h,0FEh,04h,0BDh,0A1h,0FFh

sound_71:
	defb 22h,02h,0D0h,00h,0D0h,0F0h,0D0h,00h,0F0h,10h,0F0h,30h,0F0h,60h,0F0h,0A0h
	defb 0F0h,0F0h,0F0h,00h,0F0h,0F0h,0F0h,00h,0E0h,10h,0E0h,30h,0E0h,60h,0E0h,0A0h
	defb 0E0h,0F0h,0E0h,00h,0E0h,0F0h,0E0h,00h,0D0h,10h,0D0h,30h,0D0h,60h,0D0h,0A0h
	defb 0D0h,0F0h,0D0h,00h,0D0h,0F0h,0D0h,00h,0C0h,10h,0C0h,30h,0C0h,60h,0C0h,0A0h
	defb 0C0h,0F0h,0C0h,00h,0C0h,0F0h,0C0h,00h,0B0h,10h,0B0h,30h,0B0h,60h,0B0h,0A0h
	defb 0B0h,0F0h,0B0h,00h,0B0h,0F0h,0B0h,00h,0A0h,10h,0A0h,30h,0A0h,60h,0A0h,0A0h
	defb 0A0h,0F0h,0A0h,00h,0A0h,0F0h,0A0h,00h,90h,10h,90h,30h,90h,60h,90h,0A0h
	defb 90h,0F0h,90h,00h,90h,0F0h,90h,00h,70h,10h,70h,30h,70h,60h,70h,0A0h
	defb 70h,0F0h,0FFh

sound_72:
	defb 22h,02h,0D0h,00h,0D0h,78h,0D0h,00h,0F0h,08h,0F0h,18h,0F0h,30h,0F0h,50h
	defb 0F0h,78h,0F0h,00h,0F0h,78h,0F0h,00h,0E0h,08h,0E0h,18h,0E0h,30h,0E0h,50h
	defb 0E0h,78h,0E0h,00h,0E0h,78h,0E0h,00h,0D0h,08h,0D0h,18h,0D0h,30h,0D0h,50h
	defb 0D0h,78h,0D0h,00h,0D0h,78h,0D0h,00h,0C0h,08h,0C0h,18h,0C0h,30h,0C0h,50h
	defb 0C0h,78h,0C0h,00h,0C0h,78h,0C0h,00h,0B0h,08h,0B0h,18h,0B0h,30h,0B0h,50h
	defb 0B0h,78h,0B0h,00h,0B0h,78h,0B0h,00h,0A0h,08h,0A0h,18h,0A0h,30h,0A0h,50h
	defb 0A0h,78h,0A0h,00h,0A0h,78h,0A0h,00h,90h,08h,90h,18h,90h,30h,90h,50h
	defb 90h,78h,90h,00h,90h,78h,90h,00h,70h,08h,70h,18h,70h,30h,70h,50h
	defb 70h,78h,0FFh

sound_73:
	defb 22h,01h,0E0h,80h,0E0h,0E0h,0E1h,40h,0E1h,0A0h,0E2h,00h,0E2h,60h,0F0h,0C0h
	defb 0F0h,0E0h,0F1h,00h,0F1h,20h,0F1h,40h,0F1h,60h,0F1h,80h,0F1h,0A0h,0F1h,0C0h
	defb 0F1h,0E0h,0F2h,00h,0E0h,0C0h,0E1h,20h,0E1h,80h,0E1h,0E0h,0E2h,40h,0E2h,0A0h
	defb 0D0h,0C0h,0D0h,0E0h,0D1h,00h,0D1h,20h,0D1h,40h,0D1h,60h,0D1h,80h,0D1h,0A0h
	defb 0D1h,0C0h,0D1h,0E0h,0D2h,00h,0C0h,0C0h,0C1h,20h,0C1h,80h,0C1h,0E0h,0C2h,40h
	defb 0C2h,0A0h,0B0h,0C0h,0B0h,0E0h,0B1h,00h,0B1h,20h,0B1h,40h,0B1h,60h,0B1h,80h
	defb 0B1h,0A0h,0B1h,0C0h,0B1h,0E0h,0B2h,00h,0A0h,0C0h,0A1h,20h,0A1h,80h,0A1h,0E0h
	defb 0A2h,40h,0A2h,0A0h,80h,0C0h,80h,0E0h,81h,00h,81h,20h,81h,40h,81h,60h
	defb 81h,80h,81h,0A0h,81h,0C0h,81h,0E0h,82h,00h,20h,60h,0FFh

sound_74:
	defb 0D6h,0FDh,13h,0E1h,60h,30h,0E2h,0B0h,0FEh,04h,5Ch,0A3h,0E1h,0B0h,60h,30h
	defb 0FEh,04h,66h,0A3h,0E0h,30h,0E1h,0B0h,60h,30h,60h,0B0h,0E0h,60h,30h,0E1h
	defb 0B0h,60h,0B0h,0E0h,30h,0B0h,60h,30h,60h,30h,0E1h,0B0h,0FDh,39h,0E0h,33h
	defb 0FFh

sound_75:
	defb 0D6h,0FDh,24h,0E2h,30h,0E3h,0B0h,60h,0FEh,04h,8Dh,0A3h,0E2h,60h,30h,0E3h
	defb 0B0h,0FEh,04h,96h,0A3h,0E2h,0B0h,60h,30h,0E3h,0B0h,0E2h,30h,60h,0E1h,30h
	defb 0E2h,0B0h,60h,30h,60h,0B0h,0E1h,60h,30h,0E2h,0B0h,0E1h,30h,0E2h,0B0h,60h
	defb 0FDh,39h,0B3h,0FFh

sound_76:
	defb 0D6h,0FDh,24h,0E4h,0B3h,0B0h,0B0h,0B2h,62h,0E3h,33h,30h,30h,32h,0E4h,0B2h
	defb 0FDh,24h,0E3h,63h,60h,60h,62h,0E4h,0B2h,0E3h,0B3h,0E4h,0B0h,0B0h,0B3h,0FFh

empty_sound:		; Sounds 77 to 79 point here, to the first filler byte of
			; bank 8: an 0xFF, which is the end command, so they are
			; empty. The byte is not written here: it is the start of
			; the 0xFF filler that the link puts after this module.

	end
