#!/usr/bin/env python3
"""Disassembles a piece of the cartridge, with its bank placed where it runs.

It is the shortcut for looking at a routine without generating the whole
listing: you give it the bank and the range, and it outputs the z80dasm of
those bytes with the org that bank really has (tools/banks.py). It is good
for poking around, not for publishing: what gets published is generated by
tools/mkasm.py from the trace and the notes.

Usage: disassemble.py <bank> <start> <end>   (start and end: execution addresses)
"""
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from banks import ORG, BANK_SIZE                        # noqa: E402


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    here = os.path.dirname(os.path.abspath(__file__))
    rom = open(os.path.join(here, "..", "nemesis.rom"), "rb").read()
    bank = int(sys.argv[1], 0)
    start, end = int(sys.argv[2], 0), int(sys.argv[3], 0)
    o = ORG[bank]
    if not (o <= start < end <= o + BANK_SIZE):
        sys.exit("bank %d executes at %#06x..%#06x" % (bank, o,
                                                       o + BANK_SIZE - 1))
    work = os.path.join(here, "..", "work")
    os.makedirs(work, exist_ok=True)
    tmp = os.path.join(work, "_disassemble.bin")
    off = bank * BANK_SIZE + (start - o)
    open(tmp, "wb").write(rom[off:off + (end - start)])
    # TMP/TEMP sanitised: under the msys make they arrive as '/tmp', which the
    # native Windows CRT cannot use, and z80dasm ends up writing to the root.
    r = subprocess.run(["z80dasm", "-a", "-l", "-g", hex(start), tmp],
                       capture_output=True, text=True,
                       env=dict(os.environ, TMP=work, TEMP=work))
    os.unlink(tmp)
    sys.stdout.write(r.stdout)
    sys.stderr.write(r.stderr)
    return r.returncode


if __name__ == "__main__":
    sys.exit(main())
