; ==========================================================================
; NEMESIS / GRADIUS - Konami (1986) - MSX1 - 128 KB MegaROM RC-742 (Konami4) - bank 12 (runs at 0xa000)
; ==========================================================================
; Generated by tools/mkasm.py from the actual control-flow trace.
; The comments come from tools/../src/*.notes and are anchored to an
; address, so they survive a re-trace.
; ==========================================================================

	org 0x0a000


; ----------------------------------------------------------------------
; DATA scripts_2: The scripts of stages 7 to 12 (0xA098, 0xA2D8, 0xA428,
;   0xA578 and 0xA668), pointed to by table 0x97DE in bank 11. The stretch
;   from 0xA000 to 0xA097 is the tail of the script that starts at 0x9F18, in
;   bank 11.
;   0xa000..0xb2e4  (4836 bytes)
DATA_scripts_2:
	defb 09dh,09ah,074h,001h,003h,001h	; a000
	defb 09eh,001h,079h,002h,000h,002h	; a006
	defb 09fh,003h,07fh,0b2h,0b4h,003h	; a00c
	defb 0a0h,0a6h,07eh,0b3h,0b5h,0ach	; a012
	defb 0afh,09bh,07ah,000h,001h,0aeh	; a018
	defb 0b3h,09ch,073h,003h,002h,000h	; a01e
	defb 003h,09ch,074h,001h,003h,001h	; a024
	defb 000h,09bh,079h,0aeh,0b3h,002h	; a02a
	defb 09dh,09ah,079h,0ach,0afh,0b1h	; a030
	defb 09eh,001h,080h,0aeh,0b3h,000h	; a036
	defb 09fh,002h,080h,0ach,0aeh,0a9h	; a03c
	defb 0a0h,0a6h,071h,002h,001h,002h	; a042
	defb 09dh,09ah,077h,003h,000h,003h	; a048
	defb 09eh,002h,078h,001h,003h,002h	; a04e
	defb 09fh,000h,079h,002h,001h,003h	; a054
	defb 0a0h,0a6h,080h,0b7h,0bah,0b9h	; a05a
	defb 0a7h,09bh,080h,0b8h,003h,084h	; a060
	defb 0a8h,09ch,080h,082h,083h,084h	; a066
	defb 0a7h,09ch,079h,003h,002h,0a5h	; a06c
	defb 002h,09bh,081h,001h,000h,003h	; a072
	defb 095h,09ah,085h,086h,001h,090h	; a078
	defb 096h,001h,001h,087h,003h,091h	; a07e
	defb 097h,003h,088h,08ah,08dh,092h	; a084
	defb 098h,002h,089h,08bh,08eh,093h	; a08a
	defb 099h,000h,002h,08ch,08fh,094h	; a090
	defb 003h,001h,0c0h,0bbh,0bch,0bbh	; a096
	defb 0c9h,0ceh,0c1h,0bbh,0bbh,0bbh	; a09c
	defb 0cbh,0cfh,0c2h,0bbh,0bdh,0bbh	; a0a2
	defb 0cch,0d0h,0c4h,0c6h,0bbh,0bfh	; a0a8
	defb 0cdh,0d1h,0cfh,0c7h,0beh,0bbh	; a0ae
	defb 0cdh,0cfh,0d1h,0c7h,0bbh,0bbh	; a0b4
	defb 0cch,0d0h,0c5h,0c8h,0bfh,0bbh	; a0ba
	defb 0d2h,0cfh,0c3h,0bbh,0bbh,0bbh	; a0c0
	defb 0cah,0d1h,0c4h,0c6h,0bbh,0bch	; a0c6
	defb 0cbh,0d1h,0d1h,0c7h,0bbh,0d3h	; a0cc
	defb 0d4h,0cfh,0cfh,0dah,0bbh,0cah	; a0d2
	defb 0d1h,0d1h,0d1h,0c1h,0bdh,0cah	; a0d8
	defb 0cfh,0d0h,0d0h,0c3h,0bbh,0cah	; a0de
	defb 0d0h,0cfh,0cfh,0dbh,0bbh,0d5h	; a0e4
	defb 0d6h,0d0h,0c5h,0c8h,0beh,0bbh	; a0ea
	defb 0cch,0cfh,0c1h,0bfh,0bbh,0bbh	; a0f0
	defb 0d2h,0d0h,0c2h,0bbh,0bbh,0bbh	; a0f6
	defb 0cah,0d1h,0c3h,0bbh,0bbh,0bfh	; a0fc
	defb 0cah,0cfh,0c1h,0bbh,0bbh,0bbh	; a102
	defb 0cah,0d0h,0c4h,0c6h,0bbh,0bbh	; a108
	defb 0cah,0cfh,0d0h,0c7h,0bch,0d7h	; a10e
	defb 0d8h,0d1h,0d1h,0c7h,0bbh,0cch	; a114
	defb 0cfh,0d0h,0cfh,0c7h,0bdh,0d2h	; a11a
	defb 0d1h,0d0h,0c5h,0c8h,0bbh,0d5h	; a120
	defb 0d9h,0cfh,0c4h,0c6h,0bbh,0bch	; a126
	defb 0cbh,0d1h,0d1h,0c7h,0bbh,0d3h	; a12c
	defb 0d4h,0cfh,0cfh,0dah,0bbh,0cah	; a132
	defb 0d1h,0d1h,0d1h,0c1h,0bdh,0cah	; a138
	defb 0cfh,0d0h,0d0h,0c3h,0bbh,0cah	; a13e
	defb 0d0h,0cfh,0cfh,0dbh,0bbh,0d5h	; a144
	defb 0d6h,0d0h,0c5h,0c8h,0beh,0bbh	; a14a
	defb 0cch,0cfh,0c1h,0bfh,0bbh,0bbh	; a150
	defb 0d2h,0d0h,0c2h,0bbh,0bbh,0bbh	; a156
	defb 0cah,0d1h,0c3h,0bbh,0bbh,0bfh	; a15c
	defb 0cah,0cfh,0c1h,0bbh,0bbh,0bbh	; a162
	defb 0cah,0d0h,0c4h,0c6h,0bbh,0bbh	; a168
	defb 0cah,0cfh,0d0h,0c7h,0bch,0d7h	; a16e
	defb 0d8h,0d1h,0d1h,0c7h,0bbh,0cch	; a174
	defb 0cfh,0d0h,0cfh,0c7h,0bdh,0d2h	; a17a
	defb 0d1h,0d0h,0c5h,0c8h,0bbh,0d5h	; a180
	defb 0d9h,0cfh,0c4h,0c6h,0bbh,0bch	; a186
	defb 0cbh,0d1h,0d1h,0c7h,0bbh,0d3h	; a18c
	defb 0d4h,0cfh,0cfh,0dah,0bbh,0cah	; a192
	defb 0d1h,0d1h,0d1h,0c1h,0bdh,0cah	; a198
	defb 0cfh,0d0h,0d0h,0c3h,0bbh,0cah	; a19e
	defb 0d0h,0cfh,0cfh,0dbh,0bbh,0d5h	; a1a4
	defb 0d6h,0d0h,0c5h,0c8h,0beh,0bbh	; a1aa
	defb 0cch,0cfh,0c1h,0bfh,0bbh,0bbh	; a1b0
	defb 0d2h,0d0h,0c4h,0dch,0c6h,0bdh	; a1b6
	defb 0cbh,0d0h,0d1h,0cfh,0c7h,0d3h	; a1bc
	defb 0d4h,0cfh,0cfh,0d0h,0dah,0cah	; a1c2
	defb 0cfh,0d1h,0cfh,0d1h,0c1h,0cah	; a1c8
	defb 0cfh,0cfh,0d1h,0d0h,0c2h,0cah	; a1ce
	defb 0d0h,0d1h,0cfh,0deh,0ddh,0d5h	; a1d4
	defb 0d9h,0cfh,0d0h,0c7h,0bbh,0bch	; a1da
	defb 0cah,0d0h,0d1h,0c7h,0bfh,0bbh	; a1e0
	defb 0cah,0d1h,0cfh,0dfh,0c6h,0bbh	; a1e6
	defb 0cbh,0d0h,0d0h,0d1h,0c7h,0bbh	; a1ec
	defb 0cdh,0cfh,0c5h,0e0h,0c8h,0bbh	; a1f2
	defb 0d2h,0d1h,03eh,0e1h,0e2h,0bbh	; a1f8
	defb 0e5h,0cfh,03fh,0e3h,0e4h,0beh	; a1fe
	defb 0e6h,0d0h,0c4h,0dch,0c6h,0bbh	; a204
	defb 0cbh,0d1h,0cfh,0d1h,0c7h,0bbh	; a20a
	defb 0cch,0cfh,0c5h,0e0h,0c8h,0bbh	; a210
	defb 0d2h,0d0h,0c3h,0bbh,0bbh,0bbh	; a216
	defb 0cah,0d0h,0c1h,0bbh,0bdh,0bbh	; a21c
	defb 0cah,0d1h,0c2h,0bbh,0bbh,0bbh	; a222
	defb 0cah,0cfh,0c2h,0beh,0bbh,0bfh	; a228
	defb 0cah,0d1h,0c1h,0bbh,0bbh,0bbh	; a22e
	defb 0cah,0d0h,0c3h,0bbh,0bch,0bbh	; a234
	defb 0cah,0cfh,0c2h,0bbh,0bbh,0bfh	; a23a
	defb 0cah,0d1h,0c3h,0bfh,0bbh,0bbh	; a240
	defb 0cah,0d0h,0c1h,0bdh,0bbh,0bbh	; a246
	defb 0cah,0cfh,0c2h,0bbh,0bbh,0bfh	; a24c
	defb 0cah,0d0h,0c1h,0bbh,0beh,0bbh	; a252
	defb 0cah,0d1h,0c3h,0bbh,0bfh,0bbh	; a258
	defb 0cah,0cfh,0c2h,0bch,0bbh,0bch	; a25e
	defb 0cah,0cfh,06eh,03dh,0bbh,06fh	; a264
	defb 070h,0d0h,0d1h,0c3h,0bdh,0cch	; a26a
	defb 0cfh,0d1h,0c5h,0ddh,0beh,0e7h	; a270
	defb 0d9h,0d1h,0c3h,0bbh,0bdh,0bbh	; a276
	defb 0cah,0d0h,0c2h,0bbh,0bbh,0bbh	; a27c
	defb 0cah,0cfh,0c1h,0e8h,0bbh,0bch	; a282
	defb 0f0h,0d1h,03bh,0e9h,0ech,0eeh	; a288
	defb 0f1h,0cfh,0c3h,0eah,0edh,0efh	; a28e
	defb 0f2h,0d0h,03ch,0ebh,0beh,0bbh	; a294
	defb 0f3h,0cfh,0c3h,0bfh,0bbh,0bfh	; a29a
	defb 0cah,0d1h,0c2h,0bbh,0bbh,0bbh	; a2a0
	defb 0cah,0cfh,0c3h,0bbh,0bbh,0bbh	; a2a6
	defb 0cah,0d0h,0c1h,0bbh,0bdh,0bbh	; a2ac
	defb 0cah,0d1h,0c2h,0bbh,0bbh,0bbh	; a2b2
	defb 0cah,0cfh,0c2h,0beh,0bbh,0bfh	; a2b8
	defb 0cah,0d1h,0c1h,0bbh,0bbh,0bbh	; a2be
	defb 0cah,0d0h,0c3h,0bbh,0bch,0bbh	; a2c4
	defb 0cah,0cfh,0c2h,0bbh,0bbh,0bfh	; a2ca
	defb 0cah,0d1h,0c3h,0bfh,0bbh,0bbh	; a2d0
	defb 0cah,0d0h,016h,001h,000h,002h	; a2d6
	defb 003h,01ah,017h,000h,003h,001h	; a2dc
	defb 002h,01ah,017h,001h,01ah,003h	; a2e2
	defb 000h,001h,017h,002h,016h,02ch	; a2e8
	defb 003h,039h,019h,003h,019h,02ch	; a2ee
	defb 044h,039h,003h,002h,000h,042h	; a2f4
	defb 001h,002h,000h,02ch,030h,043h	; a2fa
	defb 003h,001h,023h,02ch,001h,002h	; a300
	defb 000h,003h,026h,032h,04ch,003h	; a306
	defb 001h,04eh,03ah,04bh,04dh,030h	; a30c
	defb 032h,04fh,052h,030h,030h,030h	; a312
	defb 051h,050h,053h,030h,030h,030h	; a318
	defb 030h,030h,054h,030h,030h,030h	; a31e
	defb 030h,030h,000h,053h,030h,030h	; a324
	defb 055h,001h,001h,054h,030h,030h	; a32a
	defb 056h,002h,002h,003h,030h,045h	; a330
	defb 000h,003h,000h,002h,030h,059h	; a336
	defb 001h,000h,003h,058h,030h,030h	; a33c
	defb 05ah,002h,001h,057h,030h,030h	; a342
	defb 05ah,032h,030h,030h,030h,030h	; a348
	defb 05bh,033h,030h,030h,030h,030h	; a34e
	defb 05bh,05ch,030h,05eh,030h,030h	; a354
	defb 045h,05dh,030h,03ah,030h,030h	; a35a
	defb 05fh,000h,001h,060h,030h,030h	; a360
	defb 001h,01ch,002h,000h,030h,030h	; a366
	defb 000h,01dh,003h,001h,05eh,05eh	; a36c
	defb 016h,003h,030h,036h,03ah,03ah	; a372
	defb 018h,002h,055h,037h,060h,033h	; a378
	defb 019h,001h,056h,002h,001h,02ch	; a37e
	defb 039h,01ch,042h,02fh,032h,030h	; a384
	defb 038h,01dh,043h,031h,033h,030h	; a38a
	defb 038h,000h,000h,003h,001h,02ch	; a390
	defb 061h,02fh,001h,002h,032h,030h	; a396
	defb 065h,033h,062h,030h,031h,030h	; a39c
	defb 038h,064h,044h,030h,039h,030h	; a3a2
	defb 02fh,039h,044h,030h,039h,030h	; a3a8
	defb 033h,001h,063h,030h,003h,030h	; a3ae
	defb 02ch,002h,063h,030h,032h,030h	; a3b4
	defb 066h,067h,063h,030h,03ah,030h	; a3ba
	defb 068h,04bh,063h,030h,051h,030h	; a3c0
	defb 001h,002h,063h,030h,053h,069h	; a3c6
	defb 06ah,01ah,063h,030h,054h,030h	; a3cc
	defb 06bh,01ah,063h,030h,001h,053h	; a3d2
	defb 06ch,04dh,063h,030h,066h,002h	; a3d8
	defb 06dh,04dh,063h,030h,068h,02fh	; a3de
	defb 06eh,04dh,063h,055h,001h,060h	; a3e4
	defb 06fh,01ah,063h,056h,002h,000h	; a3ea
	defb 070h,01ah,003h,02ch,003h,001h	; a3f0
	defb 002h,04dh,023h,02ch,002h,000h	; a3f6
	defb 003h,04eh,026h,032h,04ch,001h	; a3fc
	defb 032h,04fh,03ah,04bh,04dh,030h	; a402
	defb 03ah,052h,052h,030h,030h,030h	; a408
	defb 051h,056h,053h,030h,030h,030h	; a40e
	defb 055h,003h,054h,030h,04ah,063h	; a414
	defb 056h,000h,039h,053h,04ah,063h	; a41a
	defb 001h,01ah,039h,054h,056h,071h	; a420
	defb 002h,01ah,016h,001h,002h,003h	; a426
	defb 000h,001h,017h,002h,003h,000h	; a42c
	defb 01ah,000h,018h,003h,000h,001h	; a432
	defb 01bh,01fh,019h,002h,001h,002h	; a438
	defb 01ch,020h,016h,001h,002h,001h	; a43e
	defb 01dh,021h,018h,002h,003h,000h	; a444
	defb 01eh,01fh,017h,003h,000h,001h	; a44a
	defb 01ah,000h,019h,000h,001h,002h	; a450
	defb 001h,003h,022h,023h,000h,024h	; a456
	defb 001h,002h,025h,026h,030h,027h	; a45c
	defb 023h,000h,028h,029h,001h,028h	; a462
	defb 026h,001h,02ch,02ah,003h,02ch	; a468
	defb 029h,002h,02ch,02bh,000h,02ch	; a46e
	defb 034h,032h,02dh,030h,02fh,032h	; a474
	defb 035h,033h,02dh,030h,031h,033h	; a47a
	defb 000h,001h,02ch,02eh,001h,002h	; a480
	defb 003h,000h,02ch,02fh,036h,032h	; a486
	defb 02fh,030h,000h,031h,037h,033h	; a48c
	defb 031h,030h,023h,001h,003h,02dh	; a492
	defb 038h,000h,026h,032h,02fh,02dh	; a498
	defb 038h,001h,033h,033h,031h,02ch	; a49e
	defb 039h,01ah,000h,02ch,002h,02ch	; a4a4
	defb 039h,01ah,02ch,02ch,030h,032h	; a4aa
	defb 030h,01fh,02ch,003h,030h,03ah	; a4b0
	defb 030h,01fh,02ch,032h,03bh,033h	; a4b6
	defb 001h,01ah,02ch,029h,01ah,02ch	; a4bc
	defb 003h,01ah,02ch,02ah,03ch,002h	; a4c2
	defb 002h,001h,002h,02bh,03ch,02ch	; a4c8
	defb 000h,023h,003h,002h,01ah,032h	; a4ce
	defb 03bh,026h,001h,032h,03dh,031h	; a4d4
	defb 003h,033h,02ch,03eh,01ah,039h	; a4da
	defb 000h,002h,02ch,001h,01ah,039h	; a4e0
	defb 039h,001h,001h,049h,01fh,002h	; a4e6
	defb 039h,000h,02ch,04ah,01fh,000h	; a4ec
	defb 039h,001h,02ch,03fh,041h,041h	; a4f2
	defb 016h,002h,02ch,040h,03bh,03bh	; a4f8
	defb 018h,003h,02ch,000h,002h,02ch	; a4fe
	defb 019h,002h,000h,001h,042h,02dh	; a504
	defb 038h,001h,030h,030h,043h,02dh	; a50a
	defb 038h,000h,002h,003h,038h,02ch	; a510
	defb 039h,001h,030h,032h,02fh,032h	; a516
	defb 02fh,002h,030h,033h,031h,033h	; a51c
	defb 031h,001h,000h,002h,039h,001h	; a522
	defb 000h,000h,044h,044h,044h,044h	; a528
	defb 044h,030h,044h,044h,044h,044h	; a52e
	defb 044h,030h,044h,030h,044h,044h	; a534
	defb 044h,030h,044h,030h,016h,003h	; a53a
	defb 000h,003h,044h,045h,018h,001h	; a540
	defb 002h,000h,030h,046h,047h,048h	; a546
	defb 001h,000h,002h,001h,003h,044h	; a54c
	defb 039h,003h,003h,039h,044h,044h	; a552
	defb 044h,016h,000h,044h,044h,044h	; a558
	defb 044h,017h,030h,044h,030h,044h	; a55e
	defb 044h,017h,030h,044h,039h,044h	; a564
	defb 044h,017h,030h,039h,002h,000h	; a56a
	defb 044h,019h,000h,001h,000h,001h	; a570
	defb 003h,000h,04bh,02dh,001h,02dh	; a576
	defb 000h,002h,04ch,02eh,054h,02eh	; a57c
	defb 01eh,02dh,04ch,02fh,055h,02fh	; a582
	defb 049h,02eh,024h,030h,0feh,030h	; a588
	defb 04ch,02fh,054h,002h,058h,003h	; a58e
	defb 022h,030h,055h,02dh,04dh,038h	; a594
	defb 04ch,02dh,056h,02eh,04dh,049h	; a59a
	defb 024h,02eh,057h,02fh,04dh,024h	; a5a0
	defb 0fdh,02fh,01dh,030h,04dh,054h	; a5a6
	defb 02dh,027h,01dh,04dh,04eh,055h	; a5ac
	defb 02eh,001h,046h,001h,003h,0feh	; a5b2
	defb 02fh,002h,045h,002h,000h,002h	; a5b8
	defb 030h,04dh,044h,048h,001h,003h	; a5be
	defb 001h,04dh,032h,048h,002h,000h	; a5c4
	defb 002h,04dh,032h,01dh,003h,001h	; a5ca
	defb 048h,04dh,030h,01dh,02dh,02dh	; a5d0
	defb 048h,02dh,046h,04dh,02eh,02eh	; a5d6
	defb 04dh,02eh,032h,04dh,02fh,02fh	; a5dc
	defb 000h,02fh,030h,000h,030h,030h	; a5e2
	defb 003h,027h,002h,001h,003h,000h	; a5e8
	defb 002h,001h,003h,000h,002h,001h	; a5ee
	defb 003h,000h,001h,002h,000h,002h	; a5f4
	defb 001h,002h,04bh,02dh,001h,02dh	; a5fa
	defb 000h,002h,04ch,02eh,054h,02eh	; a600
	defb 01eh,02dh,04ch,02fh,055h,02fh	; a606
	defb 049h,02eh,024h,030h,0feh,030h	; a60c
	defb 04ch,02fh,054h,002h,058h,003h	; a612
	defb 022h,030h,055h,02dh,04dh,038h	; a618
	defb 04ch,02dh,056h,02eh,04dh,049h	; a61e
	defb 024h,02eh,057h,02fh,04dh,024h	; a624
	defb 0fch,02fh,01dh,030h,04dh,054h	; a62a
	defb 02dh,027h,01dh,04dh,04eh,055h	; a630
	defb 02eh,001h,002h,001h,003h,0feh	; a636
	defb 02fh,002h,003h,000h,021h,001h	; a63c
	defb 030h,001h,001h,01dh,022h,048h	; a642
	defb 000h,003h,002h,01dh,024h,048h	; a648
	defb 002h,001h,01eh,01dh,001h,048h	; a64e
	defb 038h,000h,01fh,01dh,054h,048h	; a654
	defb 047h,002h,020h,001h,055h,048h	; a65a
	defb 020h,003h,000h,002h,0feh,048h	; a660
	defb 003h,001h,000h,001h,002h,003h	; a666
	defb 001h,05ch,07bh,02fh,003h,042h	; a66c
	defb 072h,05dh,043h,033h,071h,073h	; a672
	defb 030h,002h,001h,058h,030h,030h	; a678
	defb 030h,003h,002h,057h,030h,030h	; a67e
	defb 030h,000h,058h,030h,030h,030h	; a684
	defb 030h,072h,057h,030h,030h,030h	; a68a
	defb 045h,03bh,030h,030h,030h,063h	; a690
	defb 05fh,001h,030h,030h,030h,063h	; a696
	defb 074h,000h,053h,030h,030h,030h	; a69c
	defb 066h,067h,054h,030h,030h,030h	; a6a2
	defb 068h,04bh,05ah,053h,044h,030h	; a6a8
	defb 001h,030h,05bh,054h,044h,030h	; a6ae
	defb 058h,030h,077h,044h,044h,045h	; a6b4
	defb 076h,030h,016h,076h,044h,059h	; a6ba
	defb 030h,030h,019h,030h,044h,044h	; a6c0
	defb 05eh,030h,02fh,044h,063h,054h	; a6c6
	defb 051h,030h,033h,030h,063h,05ah	; a6cc
	defb 053h,030h,02ch,030h,063h,05bh	; a6d2
	defb 054h,030h,001h,030h,053h,030h	; a6d8
	defb 001h,053h,058h,055h,054h,030h	; a6de
	defb 05bh,000h,05eh,056h,057h,044h	; a6e4
	defb 030h,044h,060h,062h,030h,044h	; a6ea
	defb 045h,044h,039h,030h,030h,05eh	; a6f0
	defb 059h,002h,039h,045h,030h,051h	; a6f6
	defb 030h,000h,044h,07ah,055h,053h	; a6fc
	defb 063h,066h,063h,076h,05eh,054h	; a702
	defb 063h,068h,07ch,030h,033h,016h	; a708
	defb 049h,045h,044h,055h,058h,017h	; a70e
	defb 049h,030h,044h,056h,057h,018h	; a714
	defb 02ch,030h,063h,058h,030h,078h	; a71a
	defb 02ch,064h,063h,057h,030h,030h	; a720
	defb 03dh,030h,030h,030h,056h,053h	; a726
	defb 049h,01ah,030h,055h,058h,030h	; a72c
	defb 02ch,038h,030h,056h,057h,030h	; a732
	defb 05bh,039h,055h,058h,055h,053h	; a738
	defb 030h,030h,056h,057h,056h,054h	; a73e
	defb 030h,030h,07dh,030h,030h,016h	; a744
	defb 054h,01fh,07eh,044h,030h,078h	; a74a
	defb 058h,05ah,000h,044h,030h,030h	; a750
	defb 057h,076h,001h,030h,030h,055h	; a756
	defb 053h,030h,022h,079h,076h,030h	; a75c
	defb 054h,030h,025h,030h,030h,030h	; a762
	defb 030h,05eh,028h,030h,030h,030h	; a768
	defb 055h,060h,02ch,030h,030h,030h	; a76e
	defb 056h,04eh,001h,030h,030h,045h	; a774
	defb 062h,04fh,07ch,030h,030h,059h	; a77a
	defb 030h,050h,030h,030h,030h,044h	; a780
	defb 054h,030h,030h,030h,063h,044h	; a786
	defb 058h,01fh,030h,030h,063h,079h	; a78c
	defb 030h,01fh,030h,030h,030h,030h	; a792
	defb 030h,038h,030h,030h,030h,030h	; a798
	defb 030h,000h,030h,030h,030h,030h	; a79e
	defb 063h,076h,053h,030h,030h,030h	; a7a4
	defb 077h,079h,072h,055h,063h,055h	; a7aa
	defb 000h,001h,063h,056h,063h,056h	; a7b0
	defb 001h,000h,001h,000h,001h,002h	; a7b6
	defb 003h,001h,002h,001h,003h,000h	; a7bc
	defb 001h,002h,000h,01ah,01bh,01fh	; a7c2
	defb 000h,016h,003h,016h,01ch,020h	; a7c8
	defb 02ch,019h,000h,019h,01dh,021h	; a7ce
	defb 02ch,016h,003h,01ah,01eh,01fh	; a7d4
	defb 002h,019h,002h,003h,000h,003h	; a7da
	defb 000h,000h,003h,001h,002h,000h	; a7e0
	defb 001h,04eh,062h,030h,030h,030h	; a7e6
	defb 062h,04fh,030h,030h,030h,030h	; a7ec
	defb 030h,050h,030h,030h,030h,030h	; a7f2
	defb 030h,030h,030h,030h,063h,030h	; a7f8
	defb 030h,030h,030h,030h,077h,03dh	; a7fe
	defb 030h,030h,030h,030h,000h,054h	; a804
	defb 030h,030h,030h,079h,002h,001h	; a80a
	defb 030h,030h,030h,055h,053h,030h	; a810
	defb 030h,030h,030h,056h,057h,030h	; a816
	defb 030h,030h,055h,000h,030h,030h	; a81c
	defb 030h,030h,056h,058h,030h,030h	; a822
	defb 030h,030h,000h,002h,053h,030h	; a828
	defb 030h,056h,030h,039h,000h,002h	; a82e
	defb 000h,001h,030h,05bh,003h,001h	; a834
	defb 058h,030h,030h,030h,030h,030h	; a83a
	defb 030h,030h,030h,030h,030h,030h	; a840
	defb 030h,030h,030h,030h,030h,030h	; a846
	defb 030h,030h,079h,03dh,030h,030h	; a84c
	defb 030h,030h,030h,030h,030h,030h	; a852
	defb 030h,030h,030h,030h,030h,030h	; a858
	defb 030h,030h,053h,030h,039h,02ch	; a85e
	defb 030h,056h,054h,030h,030h,030h	; a864
	defb 055h,000h,001h,053h,030h,030h	; a86a
	defb 05bh,01ah,000h,054h,030h,030h	; a870
	defb 056h,01ah,04ch,000h,011h,002h	; a876
	defb 00ch,006h,001h,002h,015h,000h	; a87c
	defb 01ch,008h,001h,000h,003h,001h	; a882
	defb 01dh,005h,051h,000h,00ah,008h	; a888
	defb 006h,000h,012h,00ah,001h,002h	; a88e
	defb 007h,000h,00ch,004h,00ch,005h	; a894
	defb 001h,004h,047h,000h,00fh,008h	; a89a
	defb 008h,000h,00dh,002h,009h,000h	; a8a0
	defb 003h,001h,00ch,005h,004h,004h	; a8a6
	defb 020h,000h,009h,004h,02fh,000h	; a8ac
	defb 011h,008h,004h,000h,00bh,004h	; a8b2
	defb 008h,000h,007h,002h,014h,000h	; a8b8
	defb 009h,001h,01ah,000h,006h,002h	; a8be
	defb 00fh,000h,00bh,002h,019h,000h	; a8c4
	defb 00eh,001h,009h,000h,006h,00ah	; a8ca
	defb 001h,008h,041h,000h,00bh,001h	; a8d0
	defb 00dh,005h,001h,004h,00fh,000h	; a8d6
	defb 004h,002h,013h,00ah,004h,002h	; a8dc
	defb 005h,006h,001h,002h,013h,000h	; a8e2
	defb 02bh,001h,017h,000h,015h,008h	; a8e8
	defb 007h,000h,018h,002h,014h,000h	; a8ee
	defb 00ch,004h,01ah,006h,001h,004h	; a8f4
	defb 011h,000h,00bh,008h,005h,000h	; a8fa
	defb 024h,001h,03dh,000h,016h,002h	; a900
	defb 048h,000h,014h,001h,022h,000h	; a906
	defb 00fh,00ah,001h,002h,010h,000h	; a90c
	defb 006h,001h,01ch,005h,00bh,000h	; a912
	defb 019h,00ah,004h,002h,01ch,000h	; a918
	defb 00fh,002h,018h,000h,00dh,001h	; a91e
	defb 013h,005h,00ch,001h,003h,000h	; a924
	defb 013h,002h,022h,000h,004h,008h	; a92a
	defb 015h,00ah,005h,002h,021h,000h	; a930
	defb 011h,001h,021h,000h,009h,001h	; a936
	defb 01eh,000h,008h,002h,005h,006h	; a93c
	defb 04ah,000h,006h,002h,005h,000h	; a942
	defb 00ch,001h,004h,005h,005h,004h	; a948
	defb 00dh,000h,007h,002h,028h,000h	; a94e
	defb 005h,002h,006h,004h,002h,006h	; a954
	defb 008h,002h,002h,000h,003h,001h	; a95a
	defb 002h,000h,001h,002h,006h,006h	; a960
	defb 001h,004h,001h,005h,00dh,001h	; a966
	defb 014h,000h,00ch,001h,002h,000h	; a96c
	defb 010h,002h,014h,000h,005h,002h	; a972
	defb 022h,000h,004h,008h,006h,009h	; a978
	defb 007h,001h,002h,000h,00bh,002h	; a97e
	defb 004h,00ah,003h,008h,00eh,001h	; a984
	defb 00bh,000h,00ch,004h,00fh,000h	; a98a
	defb 00dh,001h,013h,000h,014h,002h	; a990
	defb 027h,000h,006h,008h,003h,001h	; a996
	defb 006h,005h,004h,001h,003h,009h	; a99c
	defb 005h,008h,006h,00ah,006h,002h	; a9a2
	defb 003h,006h,044h,000h,005h,002h	; a9a8
	defb 004h,006h,005h,004h,008h,000h	; a9ae
	defb 004h,004h,019h,000h,00ah,001h	; a9b4
	defb 001h,009h,010h,008h,003h,000h	; a9ba
	defb 006h,001h,005h,005h,00dh,004h	; a9c0
	defb 018h,000h,019h,002h,003h,00ah	; a9c6
	defb 003h,008h,006h,009h,00fh,000h	; a9cc
	defb 006h,004h,004h,000h,009h,001h	; a9d2
	defb 002h,005h,012h,004h,005h,000h	; a9d8
	defb 010h,001h,003h,008h,014h,00ah	; a9de
	defb 015h,002h,003h,000h,020h,001h	; a9e4
	defb 016h,005h,001h,004h,029h,006h	; a9ea
	defb 009h,002h,003h,000h,012h,001h	; a9f0
	defb 04fh,000h,003h,001h,00eh,000h	; a9f6
	defb 008h,008h,00ah,00ah,003h,008h	; a9fc
	defb 005h,009h,009h,008h,002h,000h	; aa02
	defb 01ch,004h,004h,000h,017h,001h	; aa08
	defb 003h,000h,018h,002h,005h,00ah	; aa0e
	defb 006h,008h,00ch,00ah,005h,002h	; aa14
	defb 00ah,000h,00ah,004h,00ch,005h	; aa1a
	defb 039h,001h,001h,000h,01ch,008h	; aa20
	defb 001h,000h,005h,002h,00fh,006h	; aa26
	defb 003h,002h,012h,000h,006h,002h	; aa2c
	defb 004h,00ah,003h,008h,001h,00ah	; aa32
	defb 00ah,002h,008h,006h,001h,004h	; aa38
	defb 007h,000h,003h,002h,00dh,000h	; aa3e
	defb 006h,001h,017h,000h,00ah,001h	; aa44
	defb 015h,000h,01ch,008h,004h,001h	; aa4a
	defb 004h,000h,008h,002h,003h,000h	; aa50
	defb 001h,001h,00ah,005h,001h,004h	; aa56
	defb 001h,000h,00dh,002h,005h,000h	; aa5c
	defb 00fh,002h,003h,000h,001h,001h	; aa62
	defb 009h,005h,004h,001h,007h,000h	; aa68
	defb 005h,001h,003h,009h,00eh,008h	; aa6e
	defb 005h,009h,00dh,001h,00eh,005h	; aa74
	defb 004h,001h,008h,009h,001h,008h	; aa7a
	defb 005h,000h,00dh,002h,011h,004h	; aa80
	defb 005h,000h,005h,002h,001h,000h	; aa86
	defb 001h,004h,006h,000h,00ch,008h	; aa8c
	defb 02ch,000h,014h,002h,010h,000h	; aa92
	defb 006h,002h,006h,000h,004h,001h	; aa98
	defb 00ch,005h,009h,001h,011h,005h	; aa9e
	defb 002h,001h,013h,000h,00eh,002h	; aaa4
	defb 014h,00ah,007h,002h,004h,000h	; aaaa
	defb 009h,004h,001h,000h,005h,002h	; aab0
	defb 006h,00ah,005h,008h,005h,009h	; aab6
	defb 001h,001h,011h,005h,01fh,001h	; aabc
	defb 008h,000h,001h,002h,007h,006h	; aac2
	defb 007h,002h,021h,00ah,003h,002h	; aac8
	defb 001h,006h,002h,004h,016h,005h	; aace
	defb 00ah,001h,007h,005h,003h,004h	; aad4
	defb 005h,000h,001h,001h,003h,005h	; aada
	defb 007h,000h,001h,001h,003h,005h	; aae0
	defb 015h,000h,014h,008h,002h,00ah	; aae6
	defb 004h,002h,025h,006h,002h,004h	; aaec
	defb 008h,000h,00ah,009h,024h,001h	; aaf2
	defb 001h,005h,008h,004h,004h,000h	; aaf8
	defb 012h,002h,016h,00ah,001h,008h	; aafe
	defb 002h,000h,003h,001h,010h,005h	; ab04
	defb 009h,001h,007h,009h,002h,008h	; ab0a
	defb 004h,002h,006h,006h,002h,004h	; ab10
	defb 00fh,005h,002h,001h,009h,000h	; ab16
	defb 005h,008h,006h,00ah,00ah,002h	; ab1c
	defb 00ah,006h,003h,004h,001h,000h	; ab22
	defb 014h,001h,00ah,009h,001h,001h	; ab28
	defb 003h,000h,00eh,002h,005h,006h	; ab2e
	defb 002h,004h,001h,000h,002h,001h	; ab34
	defb 010h,008h,004h,000h,004h,004h	; ab3a
	defb 002h,006h,007h,004h,004h,005h	; ab40
	defb 006h,001h,00bh,009h,005h,008h	; ab46
	defb 00ah,00ah,007h,002h,00eh,006h	; ab4c
	defb 017h,000h,00fh,002h,005h,000h	; ab52
	defb 001h,004h,002h,005h,002h,004h	; ab58
	defb 001h,000h,002h,002h,006h,00ah	; ab5e
	defb 003h,008h,00fh,001h,00bh,005h	; ab64
	defb 00eh,001h,002h,000h,001h,002h	; ab6a
	defb 00dh,006h,013h,002h,001h,004h	; ab70
	defb 003h,005h,008h,001h,008h,000h	; ab76
	defb 002h,001h,00ch,000h,010h,008h	; ab7c
	defb 007h,000h,00fh,002h,001h,00ah	; ab82
	defb 002h,008h,00ah,000h,008h,008h	; ab88
	defb 019h,000h,007h,008h,007h,000h	; ab8e
	defb 003h,001h,010h,000h,00ah,001h	; ab94
	defb 009h,005h,013h,001h,004h,000h	; ab9a
	defb 014h,002h,005h,006h,001h,002h	; aba0
	defb 016h,000h,006h,004h,005h,005h	; aba6
	defb 008h,000h,004h,005h,001h,004h	; abac
	defb 004h,000h,002h,001h,001h,004h	; abb2
	defb 001h,000h,012h,004h,00ch,005h	; abb8
	defb 02ch,000h,010h,008h,003h,000h	; abbe
	defb 009h,004h,00ch,000h,009h,002h	; abc4
	defb 002h,000h,007h,004h,012h,000h	; abca
	defb 007h,001h,001h,000h,01eh,008h	; abd0
	defb 001h,000h,010h,004h,007h,000h	; abd6
	defb 003h,002h,008h,000h,00bh,004h	; abdc
	defb 009h,000h,006h,004h,005h,000h	; abe2
	defb 005h,001h,00bh,000h,008h,001h	; abe8
	defb 016h,009h,00dh,005h,006h,004h	; abee
	defb 02dh,000h,00ah,008h,008h,00ah	; abf4
	defb 002h,000h,005h,005h,003h,000h	; abfa
	defb 005h,008h,002h,00ah,007h,002h	; ac00
	defb 009h,006h,00fh,002h,003h,000h	; ac06
	defb 007h,001h,001h,009h,002h,008h	; ac0c
	defb 002h,002h,003h,000h,008h,001h	; ac12
	defb 001h,009h,004h,008h,006h,001h	; ac18
	defb 009h,008h,001h,001h,008h,005h	; ac1e
	defb 002h,000h,005h,00ah,002h,002h	; ac24
	defb 006h,004h,008h,005h,002h,001h	; ac2a
	defb 009h,009h,001h,001h,044h,000h	; ac30
	defb 005h,001h,001h,009h,007h,008h	; ac36
	defb 006h,001h,001h,000h,008h,002h	; ac3c
	defb 00fh,006h,001h,002h,008h,000h	; ac42
	defb 004h,001h,005h,005h,006h,004h	; ac48
	defb 021h,000h,008h,002h,00eh,006h	; ac4e
	defb 003h,002h,007h,000h,012h,008h	; ac54
	defb 006h,009h,00bh,001h,012h,005h	; ac5a
	defb 002h,001h,007h,000h,005h,002h	; ac60
	defb 00fh,00ah,001h,008h,001h,000h	; ac66
	defb 010h,001h,002h,008h,00bh,00ah	; ac6c
	defb 019h,002h,003h,006h,001h,004h	; ac72
	defb 001h,005h,019h,001h,00ah,005h	; ac78
	defb 003h,004h,02ch,000h,006h,008h	; ac7e
	defb 006h,00ah,005h,002h,011h,006h	; ac84
	defb 004h,004h,008h,000h,013h,008h	; ac8a
	defb 001h,000h,00fh,001h,00bh,005h	; ac90
	defb 001h,001h,01ah,000h,00ah,001h	; ac96
	defb 001h,009h,004h,008h,010h,002h	; ac9c
	defb 012h,00ah,002h,002h,003h,004h	; aca2
	defb 011h,005h,013h,004h,008h,000h	; aca8
	defb 011h,001h,005h,008h,018h,00ah	; acae
	defb 008h,002h,001h,006h,003h,004h	; acb4
	defb 015h,005h,00ch,001h,004h,009h	; acba
	defb 002h,008h,004h,00ah,012h,002h	; acc0
	defb 00ah,006h,00bh,000h,023h,008h	; acc6
	defb 003h,009h,01eh,001h,00fh,005h	; accc
	defb 00ch,004h,022h,002h,003h,00ah	; acd2
	defb 014h,008h,001h,00ah,003h,002h	; acd8
	defb 02ah,000h,00bh,008h,005h,009h	; acde
	defb 00dh,001h,00dh,005h,008h,004h	; ace4
	defb 020h,006h,004h,004h,00eh,000h	; acea
	defb 007h,008h,00fh,009h,005h,008h	; acf0
	defb 00ch,00ah,009h,008h,002h,009h	; acf6
	defb 009h,001h,010h,005h,009h,001h	; acfc
	defb 00eh,000h,003h,004h,001h,006h	; ad02
	defb 002h,002h,014h,00ah,003h,002h	; ad08
	defb 002h,006h,017h,004h,002h,000h	; ad0e
	defb 004h,008h,00bh,009h,002h,000h	; ad14
	defb 005h,004h,004h,000h,00ah,008h	; ad1a
	defb 002h,009h,003h,008h,006h,00ah	; ad20
	defb 005h,002h,005h,006h,01eh,004h	; ad26
	defb 002h,006h,004h,002h,001h,00ah	; ad2c
	defb 00ah,008h,005h,009h,016h,001h	; ad32
	defb 001h,005h,010h,004h,006h,005h	; ad38
	defb 001h,001h,02fh,000h,02ah,008h	; ad3e
	defb 004h,00ah,004h,002h,016h,006h	; ad44
	defb 003h,002h,007h,000h,005h,008h	; ad4a
	defb 002h,000h,005h,008h,003h,009h	; ad50
	defb 004h,001h,00ch,005h,00eh,004h	; ad56
	defb 00ah,005h,00ah,001h,001h,000h	; ad5c
	defb 012h,002h,015h,00ah,009h,008h	; ad62
	defb 008h,009h,005h,001h,012h,005h	; ad68
	defb 008h,004h,00eh,006h,00fh,002h	; ad6e
	defb 003h,008h,00ah,009h,001h,008h	; ad74
	defb 012h,000h,008h,008h,00ch,00ah	; ad7a
	defb 002h,008h,004h,000h,001h,001h	; ad80
	defb 007h,005h,00dh,004h,012h,006h	; ad86
	defb 000h,000h,000h,000h,000h,000h	; ad8c
	defb 000h,000h,030h,000h,005h,00ah	; ad92
	defb 015h,000h,007h,008h,008h,000h	; ad98
	defb 001h,001h,00dh,005h,003h,004h	; ad9e
	defb 007h,000h,009h,002h,002h,006h	; ada4
	defb 011h,004h,01dh,000h,014h,002h	; adaa
	defb 005h,006h,001h,004h,00dh,000h	; adb0
	defb 00ah,008h,009h,009h,004h,001h	; adb6
	defb 00eh,005h,004h,001h,013h,000h	; adbc
	defb 007h,008h,008h,00ah,002h,002h	; adc2
	defb 002h,004h,008h,005h,002h,004h	; adc8
	defb 001h,000h,003h,002h,00ah,00ah	; adce
	defb 005h,008h,00ah,001h,00bh,005h	; add4
	defb 011h,000h,008h,00ah,004h,002h	; adda
	defb 00bh,004h,00dh,000h,004h,004h	; ade0
	defb 018h,000h,00dh,008h,005h,00ah	; ade6
	defb 00bh,002h,005h,006h,005h,004h	; adec
	defb 003h,000h,022h,001h,018h,000h	; adf2
	defb 009h,002h,011h,006h,005h,002h	; adf8
	defb 001h,00ah,004h,008h,00bh,009h	; adfe
	defb 009h,001h,009h,005h,003h,001h	; ae04
	defb 004h,009h,001h,008h,002h,000h	; ae0a
	defb 010h,002h,009h,00ah,001h,002h	; ae10
	defb 001h,000h,00bh,005h,001h,001h	; ae16
	defb 002h,000h,00bh,008h,002h,000h	; ae1c
	defb 010h,004h,01ah,000h,012h,009h	; ae22
	defb 004h,008h,00ah,00ah,005h,002h	; ae28
	defb 019h,006h,002h,002h,010h,000h	; ae2e
	defb 027h,001h,001h,000h,001h,008h	; ae34
	defb 00ch,00ah,006h,002h,008h,006h	; ae3a
	defb 008h,002h,00ch,00ah,003h,008h	; ae40
	defb 00dh,009h,00eh,008h,001h,002h	; ae46
	defb 008h,006h,014h,004h,005h,005h	; ae4c
	defb 009h,004h,001h,005h,004h,001h	; ae52
	defb 016h,009h,005h,001h,006h,005h	; ae58
	defb 017h,004h,00dh,000h,004h,001h	; ae5e
	defb 005h,004h,008h,000h,007h,004h	; ae64
	defb 019h,000h,003h,008h,009h,000h	; ae6a
	defb 006h,009h,008h,008h,00fh,00ah	; ae70
	defb 004h,008h,009h,009h,002h,008h	; ae76
	defb 006h,000h,02bh,004h,005h,006h	; ae7c
	defb 002h,004h,009h,000h,00eh,008h	; ae82
	defb 003h,009h,009h,008h,002h,00ah	; ae88
	defb 004h,008h,005h,000h,006h,00ah	; ae8e
	defb 009h,008h,001h,009h,002h,001h	; ae94
	defb 002h,004h,002h,006h,002h,00ah	; ae9a
	defb 005h,008h,002h,001h,00eh,005h	; aea0
	defb 002h,004h,001h,000h,001h,002h	; aea6
	defb 004h,00ah,002h,002h,005h,004h	; aeac
	defb 004h,000h,005h,001h,00ah,000h	; aeb2
	defb 004h,001h,001h,000h,008h,002h	; aeb8
	defb 003h,00ah,001h,008h,001h,000h	; aebe
	defb 015h,004h,001h,005h,001h,001h	; aec4
	defb 009h,000h,011h,004h,008h,000h	; aeca
	defb 007h,002h,006h,000h,003h,002h	; aed0
	defb 00fh,000h,001h,001h,003h,005h	; aed6
	defb 009h,000h,003h,001h,010h,000h	; aedc
	defb 004h,001h,008h,000h,010h,008h	; aee2
	defb 00bh,00ah,001h,002h,00ch,000h	; aee8
	defb 006h,002h,00fh,004h,00ch,000h	; aeee
	defb 005h,002h,00fh,000h,00ah,005h	; aef4
	defb 001h,004h,010h,000h,00eh,008h	; aefa
	defb 005h,001h,008h,005h,004h,001h	; af00
	defb 001h,000h,003h,004h,002h,000h	; af06
	defb 003h,002h,003h,000h,002h,001h	; af0c
	defb 005h,008h,009h,000h,002h,001h	; af12
	defb 002h,000h,004h,002h,006h,006h	; af18
	defb 009h,004h,029h,000h,002h,008h	; af1e
	defb 003h,000h,003h,004h,009h,000h	; af24
	defb 00eh,00ah,001h,002h,003h,006h	; af2a
	defb 004h,002h,002h,00ah,002h,008h	; af30
	defb 006h,001h,008h,000h,006h,004h	; af36
	defb 006h,005h,004h,004h,002h,000h	; af3c
	defb 001h,002h,002h,000h,001h,008h	; af42
	defb 004h,009h,013h,001h,005h,000h	; af48
	defb 001h,002h,002h,006h,004h,000h	; af4e
	defb 056h,000h,01fh,001h,015h,000h	; af54
	defb 02fh,008h,002h,000h,012h,004h	; af5a
	defb 019h,006h,01ch,004h,01ah,006h	; af60
	defb 003h,002h,002h,00ah,003h,008h	; af66
	defb 00ch,000h,00ch,008h,004h,000h	; af6c
	defb 005h,002h,030h,000h,00bh,008h	; af72
	defb 001h,009h,010h,001h,016h,005h	; af78
	defb 007h,001h,00fh,000h,003h,002h	; af7e
	defb 006h,00ah,018h,008h,004h,009h	; af84
	defb 003h,001h,013h,005h,002h,004h	; af8a
	defb 00fh,000h,00dh,002h,00ah,006h	; af90
	defb 006h,000h,009h,001h,013h,009h	; af96
	defb 00eh,000h,010h,002h,027h,006h	; af9c
	defb 021h,000h,009h,009h,004h,008h	; afa2
	defb 006h,00ah,008h,002h,00dh,000h	; afa8
	defb 01ch,001h,002h,000h,01dh,002h	; afae
	defb 011h,000h,013h,008h,00ch,000h	; afb4
	defb 018h,001h,065h,000h,008h,001h	; afba
	defb 00eh,000h,013h,008h,067h,000h	; afc0
	defb 006h,009h,003h,008h,009h,000h	; afc6
	defb 018h,004h,00ah,006h,004h,004h	; afcc
	defb 004h,000h,001h,002h,007h,006h	; afd2
	defb 001h,004h,005h,000h,007h,002h	; afd8
	defb 008h,000h,003h,002h,004h,004h	; afde
	defb 015h,000h,00bh,001h,012h,000h	; afe4
	defb 008h,001h,009h,000h,008h,001h	; afea
	defb 006h,000h,001h,004h,00ah,005h	; aff0
	defb 010h,004h,011h,000h,005h,001h	; aff6
	defb 002h,000h,005h,002h,010h,00ah	; affc
	defb 00dh,008h,01dh,000h,007h,006h	; b002
	defb 010h,004h,001h,000h,009h,002h	; b008
	defb 005h,000h,001h,008h,002h,00ah	; b00e
	defb 001h,008h,004h,000h,008h,008h	; b014
	defb 002h,009h,002h,001h,001h,005h	; b01a
	defb 005h,004h,007h,006h,003h,004h	; b020
	defb 028h,005h,002h,001h,002h,009h	; b026
	defb 01ah,008h,005h,000h,006h,004h	; b02c
	defb 007h,000h,005h,002h,007h,000h	; b032
	defb 00ah,004h,003h,000h,00eh,002h	; b038
	defb 002h,00ah,005h,008h,005h,009h	; b03e
	defb 007h,008h,00eh,000h,001h,002h	; b044
	defb 007h,00ah,002h,002h,001h,000h	; b04a
	defb 00ah,004h,00ch,005h,004h,004h	; b050
	defb 015h,000h,001h,001h,002h,005h	; b056
	defb 002h,000h,019h,00ah,002h,008h	; b05c
	defb 001h,000h,003h,001h,001h,000h	; b062
	defb 004h,002h,005h,000h,00bh,002h	; b068
	defb 001h,000h,010h,004h,006h,005h	; b06e
	defb 00ch,004h,013h,000h,04dh,000h	; b074
	defb 00dh,001h,00bh,000h,00bh,002h	; b07a
	defb 014h,006h,001h,004h,013h,000h	; b080
	defb 016h,008h,002h,001h,018h,005h	; b086
	defb 023h,000h,00ch,008h,00ah,000h	; b08c
	defb 00dh,002h,006h,000h,00bh,004h	; b092
	defb 04ch,000h,00bh,008h,003h,000h	; b098
	defb 00ah,001h,00eh,000h,014h,004h	; b09e
	defb 072h,000h,009h,008h,00ah,000h	; b0a4
	defb 013h,002h,016h,000h,017h,001h	; b0aa
	defb 03ah,000h,01ch,002h,012h,000h	; b0b0
	defb 019h,001h,006h,009h,003h,008h	; b0b6
	defb 016h,000h,018h,002h,004h,00ah	; b0bc
	defb 003h,008h,026h,001h,004h,009h	; b0c2
	defb 004h,008h,001h,00ah,02ah,002h	; b0c8
	defb 016h,000h,003h,001h,009h,009h	; b0ce
	defb 013h,001h,01ah,000h,001h,002h	; b0d4
	defb 023h,006h,002h,004h,02eh,000h	; b0da
	defb 028h,001h,00eh,000h,00dh,002h	; b0e0
	defb 013h,00ah,001h,008h,027h,000h	; b0e6
	defb 005h,008h,005h,000h,007h,002h	; b0ec
	defb 00fh,000h,025h,001h,01bh,000h	; b0f2
	defb 014h,002h,003h,006h,008h,004h	; b0f8
	defb 010h,000h,006h,001h,017h,000h	; b0fe
	defb 008h,001h,02dh,000h,005h,001h	; b104
	defb 018h,000h,01dh,002h,00ah,000h	; b10a
	defb 008h,004h,004h,005h,017h,000h	; b110
	defb 014h,001h,014h,000h,008h,008h	; b116
	defb 006h,000h,00fh,002h,023h,000h	; b11c
	defb 009h,008h,00ch,000h,013h,004h	; b122
	defb 017h,000h,008h,008h,00ch,000h	; b128
	defb 004h,001h,004h,009h,001h,008h	; b12e
	defb 009h,000h,00ah,008h,009h,000h	; b134
	defb 049h,000h,005h,002h,007h,000h	; b13a
	defb 00ch,001h,002h,005h,003h,004h	; b140
	defb 008h,006h,002h,004h,00ah,000h	; b146
	defb 007h,004h,00bh,006h,010h,000h	; b14c
	defb 00ah,008h,010h,001h,003h,005h	; b152
	defb 003h,004h,00eh,000h,017h,002h	; b158
	defb 00eh,000h,002h,001h,00ah,009h	; b15e
	defb 00ch,001h,012h,000h,002h,002h	; b164
	defb 00dh,006h,001h,002h,00fh,000h	; b16a
	defb 01bh,001h,002h,009h,008h,000h	; b170
	defb 009h,002h,018h,00ah,004h,002h	; b176
	defb 006h,000h,005h,002h,001h,006h	; b17c
	defb 004h,004h,005h,005h,003h,001h	; b182
	defb 00eh,009h,007h,008h,008h,000h	; b188
	defb 001h,002h,004h,006h,002h,004h	; b18e
	defb 006h,000h,00fh,001h,002h,005h	; b194
	defb 023h,000h,007h,00ah,010h,002h	; b19a
	defb 00ch,000h,00dh,004h,007h,005h	; b1a0
	defb 002h,004h,002h,006h,004h,002h	; b1a6
	defb 004h,000h,00bh,001h,00bh,009h	; b1ac
	defb 006h,008h,00ah,00ah,004h,002h	; b1b2
	defb 005h,006h,019h,004h,01eh,000h	; b1b8
	defb 00fh,002h,001h,000h,003h,008h	; b1be
	defb 003h,009h,00ch,001h,00eh,005h	; b1c4
	defb 007h,001h,004h,002h,00ch,00ah	; b1ca
	defb 016h,008h,004h,000h,023h,004h	; b1d0
	defb 00ah,000h,007h,008h,004h,009h	; b1d6
	defb 00ch,008h,002h,00ah,004h,002h	; b1dc
	defb 002h,006h,00ah,004h,007h,000h	; b1e2
	defb 002h,005h,001h,000h,00ah,008h	; b1e8
	defb 006h,000h,001h,008h,003h,00ah	; b1ee
	defb 006h,002h,012h,000h,008h,008h	; b1f4
	defb 003h,009h,00dh,001h,002h,000h	; b1fa
	defb 002h,004h,00bh,006h,00ch,004h	; b200
	defb 008h,000h,008h,008h,00ah,00ah	; b206
	defb 001h,008h,001h,000h,00fh,001h	; b20c
	defb 005h,005h,007h,004h,004h,000h	; b212
	defb 008h,004h,00ch,005h,002h,001h	; b218
	defb 002h,008h,010h,00ah,001h,002h	; b21e
	defb 00eh,000h,007h,001h,00dh,000h	; b224
	defb 012h,008h,00ch,000h,00ah,004h	; b22a
	defb 007h,006h,00bh,004h,009h,005h	; b230
	defb 021h,000h,002h,001h,009h,000h	; b236
	defb 004h,002h,008h,000h,003h,001h	; b23c
	defb 004h,000h,006h,008h,015h,00ah	; b242
	defb 001h,008h,011h,000h,008h,008h	; b248
	defb 002h,000h,00eh,001h,001h,000h	; b24e
	defb 004h,008h,002h,00ah,003h,002h	; b254
	defb 00ch,006h,00ch,004h,002h,000h	; b25a
	defb 009h,008h,003h,000h,003h,004h	; b260
	defb 001h,005h,002h,001h,004h,000h	; b266
	defb 003h,001h,00bh,005h,002h,001h	; b26c
	defb 003h,000h,001h,002h,004h,00ah	; b272
	defb 001h,002h,025h,000h,002h,004h	; b278
	defb 003h,006h,004h,004h,009h,000h	; b27e
	defb 014h,008h,009h,009h,003h,000h	; b284
	defb 008h,006h,001h,000h,001h,001h	; b28a
	defb 002h,009h,001h,001h,001h,005h	; b290
	defb 004h,004h,008h,006h,005h,004h	; b296
	defb 006h,005h,002h,001h,008h,009h	; b29c
	defb 007h,001h,001h,000h,00eh,002h	; b2a2
	defb 004h,00ah,00ah,000h,004h,008h	; b2a8
	defb 006h,000h,001h,001h,00fh,005h	; b2ae
	defb 001h,001h,001h,000h,009h,00ah	; b2b4
	defb 00dh,000h,008h,002h,014h,000h	; b2ba
	defb 009h,005h,001h,001h,006h,000h	; b2c0
	defb 015h,008h,006h,00ah,00ch,002h	; b2c6
	defb 001h,006h,00bh,004h,001h,006h	; b2cc
	defb 001h,002h,007h,000h,005h,001h	; b2d2
	defb 007h,009h,00dh,008h,003h,000h	; b2d8
	defb 00ah,004h,002h,000h,009h,008h	; b2de

; ----------------------------------------------------------------------
; DATA endings_table: Four words (0xB2EC, 0xB379, 0xB3F4, 0xB48A). Read by
;   0x5D95 in bank 0 with `ld hl,0xB2D2` and 0x47AE, that is, with the base
;   declared EIGHT WORDS further back: only indices 9 to 12 are valid, and the
;   entries for stages 1 to 8 would land on top of the previous script. It is
;   the same trick as table 0x42AD.
;   0xb2e4..0xb2ec  (8 bytes)
DATA_endings_table:
	defw 0b2ech,0b379h	; b2e4  -> DATA_ending_records 0xb379
	defw 0b3f4h,0b48ah	; b2e8

; ----------------------------------------------------------------------
; DATA ending_records: What the table above points to: groups of three bytes
;   (a count, and a word) that 0x5DAA reads with `ld c,(hl) / ld e,(hl) / ld
;   d,(hl)`.
;   0xb2ec..0xb649  (861 bytes)
DATA_ending_records:
	defb 041h,050h,000h	; b2ec
	defb 041h,052h,000h	; b2ef
	defb 041h,054h,000h	; b2f2
	defb 040h,056h,000h	; b2f5
	defb 015h,058h,000h	; b2f8
	defb 015h,05ah,000h	; b2fb
	defb 025h,05ah,000h	; b2fe
	defb 025h,05ch,000h	; b301
	defb 025h,05eh,000h	; b304
	defb 025h,060h,000h	; b307
	defb 015h,062h,000h	; b30a
	defb 025h,062h,000h	; b30d
	defb 015h,064h,000h	; b310
	defb 061h,06ah,000h	; b313
	defb 031h,06ch,000h	; b316
	defb 061h,06eh,000h	; b319
	defb 008h,072h,000h	; b31c
	defb 061h,072h,000h	; b31f
	defb 049h,07ch,000h	; b322
	defb 049h,07eh,000h	; b325
	defb 015h,098h,000h	; b328
	defb 015h,09ah,000h	; b32b
	defb 04dh,0a7h,000h	; b32e
	defb 04dh,0a9h,000h	; b331
	defb 008h,0aah,000h	; b334
	defb 04dh,0abh,000h	; b337
	defb 04dh,0adh,000h	; b33a
	defb 04dh,0afh,000h	; b33d
	defb 009h,0b6h,000h	; b340
	defb 069h,0bah,000h	; b343
	defb 009h,0beh,000h	; b346
	defb 029h,0c2h,000h	; b349
	defb 009h,0c6h,000h	; b34c
	defb 028h,0cah,000h	; b34f
	defb 05dh,0cah,000h	; b352
	defb 05dh,0cch,000h	; b355
	defb 06dh,0cch,000h	; b358
	defb 009h,0ceh,000h	; b35b
	defb 06dh,0ceh,000h	; b35e
	defb 008h,0d6h,000h	; b361
	defb 031h,0f2h,000h	; b364
	defb 031h,0f4h,000h	; b367
	defb 031h,0f6h,000h	; b36a
	defb 031h,0f8h,000h	; b36d
	defb 068h,0fah,000h	; b370
	defb 056h,0fch,000h	; b373
	defb 0ffh,0ffh,0ffh	; b376
	defb 005h,049h,000h	; b379
	defb 00dh,04bh,000h	; b37c
	defb 005h,04dh,000h	; b37f
	defb 00dh,04fh,000h	; b382
	defb 005h,05ah,000h	; b385
	defb 00dh,05ch,000h	; b388
	defb 005h,05eh,000h	; b38b
	defb 06dh,068h,000h	; b38e
	defb 06dh,06ah,000h	; b391
	defb 06dh,06ch,000h	; b394
	defb 06dh,06eh,000h	; b397
	defb 03dh,084h,000h	; b39a
	defb 02ch,086h,000h	; b39d
	defb 03dh,086h,000h	; b3a0
	defb 03dh,098h,000h	; b3a3
	defb 02dh,09ah,000h	; b3a6
	defb 03dh,09ah,000h	; b3a9
	defb 02dh,09ch,000h	; b3ac
	defb 039h,0a4h,000h	; b3af
	defb 020h,0a6h,000h	; b3b2
	defb 038h,0a6h,000h	; b3b5
	defb 056h,0b8h,000h	; b3b8
	defb 031h,0cdh,000h	; b3bb
	defb 031h,0cfh,000h	; b3be
	defb 030h,0d1h,000h	; b3c1
	defb 051h,0d1h,000h	; b3c4
	defb 031h,0d3h,000h	; b3c7
	defb 031h,0d5h,000h	; b3ca
	defb 011h,0d6h,000h	; b3cd
	defb 029h,0d9h,000h	; b3d0
	defb 021h,0dbh,000h	; b3d3
	defb 019h,0ddh,000h	; b3d6
	defb 051h,0eah,000h	; b3d9
	defb 051h,0ech,000h	; b3dc
	defb 051h,0eeh,000h	; b3df
	defb 038h,0f1h,000h	; b3e2
	defb 031h,0f3h,000h	; b3e5
	defb 031h,0f5h,000h	; b3e8
	defb 009h,0f9h,000h	; b3eb
	defb 091h,0f9h,000h	; b3ee
	defb 0ffh,0ffh,0ffh	; b3f1
	defb 005h,03bh,000h	; b3f4
	defb 075h,03ch,000h	; b3f7
	defb 005h,03dh,000h	; b3fa
	defb 034h,03eh,000h	; b3fd
	defb 075h,03eh,000h	; b400
	defb 005h,03fh,000h	; b403
	defb 094h,040h,000h	; b406
	defb 005h,041h,000h	; b409
	defb 005h,043h,000h	; b40c
	defb 0a5h,044h,000h	; b40f
	defb 0a5h,046h,000h	; b412
	defb 0a5h,048h,000h	; b415
	defb 095h,04ah,000h	; b418
	defb 0a5h,04ah,000h	; b41b
	defb 095h,04ch,000h	; b41e
	defb 095h,04eh,000h	; b421
	defb 095h,050h,000h	; b424
	defb 095h,052h,000h	; b427
	defb 0a0h,054h,000h	; b42a
	defb 010h,055h,000h	; b42d
	defb 055h,056h,000h	; b430
	defb 065h,056h,000h	; b433
	defb 0a0h,056h,000h	; b436
	defb 045h,058h,000h	; b439
	defb 055h,058h,000h	; b43c
	defb 065h,058h,000h	; b43f
	defb 075h,058h,000h	; b442
	defb 0a2h,058h,000h	; b445
	defb 012h,059h,000h	; b448
	defb 045h,05ah,000h	; b44b
	defb 055h,05ah,000h	; b44e
	defb 065h,05ah,000h	; b451
	defb 075h,05ah,000h	; b454
	defb 015h,05bh,000h	; b457
	defb 055h,05ch,000h	; b45a
	defb 075h,05ch,000h	; b45d
	defb 015h,05dh,000h	; b460
	defb 055h,066h,000h	; b463
	defb 055h,068h,000h	; b466
	defb 055h,06ah,000h	; b469
	defb 035h,078h,000h	; b46c
	defb 05dh,078h,000h	; b46f
	defb 045h,07ah,000h	; b472
	defb 055h,07ah,000h	; b475
	defb 030h,09dh,000h	; b478
	defb 045h,0aeh,000h	; b47b
	defb 045h,0b0h,000h	; b47e
	defb 045h,0b2h,000h	; b481
	defb 055h,0bdh,000h	; b484
	defb 0ffh,0ffh,0ffh	; b487
	defb 014h,028h,000h	; b48a
	defb 02dh,02ch,000h	; b48d
	defb 025h,02eh,000h	; b490
	defb 0a5h,02eh,000h	; b493
	defb 0a5h,030h,000h	; b496
	defb 0a5h,032h,000h	; b499
	defb 081h,038h,000h	; b49c
	defb 0a5h,03ch,000h	; b49f
	defb 051h,03dh,000h	; b4a2
	defb 0a5h,03eh,000h	; b4a5
	defb 051h,03fh,000h	; b4a8
	defb 0a5h,040h,000h	; b4ab
	defb 051h,041h,000h	; b4ae
	defb 051h,043h,000h	; b4b1
	defb 031h,044h,000h	; b4b4
	defb 031h,046h,000h	; b4b7
	defb 069h,04ah,000h	; b4ba
	defb 061h,04ch,000h	; b4bd
	defb 071h,052h,000h	; b4c0
	defb 061h,054h,000h	; b4c3
	defb 00dh,057h,000h	; b4c6
	defb 081h,058h,000h	; b4c9
	defb 015h,059h,000h	; b4cc
	defb 071h,059h,000h	; b4cf
	defb 00ch,068h,000h	; b4d2
	defb 00dh,06ah,000h	; b4d5
	defb 00dh,06ch,000h	; b4d8
	defb 059h,06ch,000h	; b4db
	defb 059h,072h,000h	; b4de
	defb 061h,07ch,000h	; b4e1
	defb 0a5h,07ch,000h	; b4e4
	defb 090h,07dh,000h	; b4e7
	defb 0a5h,07eh,000h	; b4ea
	defb 090h,07fh,000h	; b4ed
	defb 010h,084h,000h	; b4f0
	defb 010h,086h,000h	; b4f3
	defb 008h,088h,000h	; b4f6
	defb 008h,08ah,000h	; b4f9
	defb 099h,08eh,000h	; b4fc
	defb 099h,090h,000h	; b4ff
	defb 0a1h,092h,000h	; b502
	defb 0a1h,094h,000h	; b505
	defb 0a1h,096h,000h	; b508
	defb 009h,098h,000h	; b50b
	defb 051h,098h,000h	; b50e
	defb 009h,09ah,000h	; b511
	defb 051h,09ch,000h	; b514
	defb 091h,09ch,000h	; b517
	defb 091h,09eh,000h	; b51a
	defb 031h,0a2h,000h	; b51d
	defb 021h,0a4h,000h	; b520
	defb 011h,0a6h,000h	; b523
	defb 061h,0a8h,000h	; b526
	defb 051h,0ach,000h	; b529
	defb 091h,0aeh,000h	; b52c
	defb 041h,0b0h,000h	; b52f
	defb 081h,0b0h,000h	; b532
	defb 005h,0bah,000h	; b535
	defb 015h,0bch,000h	; b538
	defb 071h,0bch,000h	; b53b
	defb 015h,0beh,000h	; b53e
	defb 061h,0beh,000h	; b541
	defb 0a1h,0beh,000h	; b544
	defb 084h,0c6h,000h	; b547
	defb 031h,0c8h,000h	; b54a
	defb 021h,0cah,000h	; b54d
	defb 00dh,0cdh,000h	; b550
	defb 00dh,0cfh,000h	; b553
	defb 081h,0d0h,000h	; b556
	defb 00dh,0d1h,000h	; b559
	defb 071h,0d2h,000h	; b55c
	defb 061h,0d4h,000h	; b55f
	defb 071h,0dah,000h	; b562
	defb 0a1h,0dah,000h	; b565
	defb 084h,0dch,000h	; b568
	defb 009h,0dch,000h	; b56b
	defb 071h,0dch,000h	; b56e
	defb 0a1h,0dch,000h	; b571
	defb 08ch,0deh,000h	; b574
	defb 009h,0deh,000h	; b577
	defb 071h,0deh,000h	; b57a
	defb 0a1h,0deh,000h	; b57d
	defb 08ch,0e0h,000h	; b580
	defb 071h,0e0h,000h	; b583
	defb 084h,0e2h,000h	; b586
	defb 071h,0e2h,000h	; b589
	defb 091h,0e6h,000h	; b58c
	defb 081h,0e8h,000h	; b58f
	defb 071h,0eah,000h	; b592
	defb 061h,0ech,000h	; b595
	defb 051h,0eeh,000h	; b598
	defb 041h,0f0h,000h	; b59b
	defb 0a0h,0f2h,000h	; b59e
	defb 031h,0f2h,000h	; b5a1
	defb 021h,0f4h,000h	; b5a4
	defb 011h,0f6h,000h	; b5a7
	defb 010h,024h,001h	; b5aa
	defb 080h,024h,001h	; b5ad
	defb 011h,026h,001h	; b5b0
	defb 099h,026h,001h	; b5b3
	defb 011h,028h,001h	; b5b6
	defb 011h,02ah,001h	; b5b9
	defb 041h,02ah,001h	; b5bc
	defb 051h,02ah,001h	; b5bf
	defb 031h,02ch,001h	; b5c2
	defb 061h,02ch,001h	; b5c5
	defb 099h,02ch,001h	; b5c8
	defb 099h,030h,001h	; b5cb
	defb 04dh,033h,001h	; b5ce
	defb 089h,034h,001h	; b5d1
	defb 081h,038h,001h	; b5d4
	defb 061h,03ch,001h	; b5d7
	defb 071h,03ch,001h	; b5da
	defb 029h,03eh,001h	; b5dd
	defb 061h,03eh,001h	; b5e0
	defb 071h,03eh,001h	; b5e3
	defb 019h,040h,001h	; b5e6
	defb 009h,042h,001h	; b5e9
	defb 0a1h,048h,001h	; b5ec
	defb 0a1h,04ah,001h	; b5ef
	defb 091h,04ch,001h	; b5f2
	defb 061h,04eh,001h	; b5f5
	defb 071h,04eh,001h	; b5f8
	defb 081h,04eh,001h	; b5fb
	defb 010h,054h,001h	; b5fe
	defb 018h,058h,001h	; b601
	defb 0a1h,05ah,001h	; b604
	defb 020h,05ch,001h	; b607
	defb 071h,05ch,001h	; b60a
	defb 0a1h,05ch,001h	; b60d
	defb 099h,05eh,001h	; b610
	defb 028h,060h,001h	; b613
	defb 091h,060h,001h	; b616
	defb 089h,062h,001h	; b619
	defb 031h,064h,001h	; b61c
	defb 081h,064h,001h	; b61f
	defb 071h,066h,001h	; b622
	defb 061h,068h,001h	; b625
	defb 020h,06ah,001h	; b628
	defb 051h,06ah,001h	; b62b
	defb 010h,06ch,001h	; b62e
	defb 041h,06ch,001h	; b631
	defb 000h,06eh,001h	; b634
	defb 071h,074h,001h	; b637
	defb 069h,076h,001h	; b63a
	defb 061h,078h,001h	; b63d
	defb 059h,07ah,001h	; b640
	defb 051h,07ch,001h	; b643
	defb 041h,07eh,001h	; b646

; ----------------------------------------------------------------------
; DATA filler: 0xFF filler up to the bank's 8192 bytes.
;   0xb649..0xc000  (2487 bytes)
DATA_filler:
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b649  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b659  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b669  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b679  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b689  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b699  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b6a9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b6b9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b6c9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b6d9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b6e9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b6f9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b709  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b719  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b729  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b739  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b749  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b759  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b769  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b779  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b789  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b799  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b7a9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b7b9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b7c9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b7d9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b7e9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b7f9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b809  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b819  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b829  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b839  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b849  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b859  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b869  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b879  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b889  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b899  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b8a9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b8b9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b8c9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b8d9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b8e9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b8f9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b909  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b919  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b929  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b939  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b949  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b959  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b969  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b979  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b989  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b999  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b9a9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b9b9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b9c9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b9d9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b9e9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; b9f9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba09  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba19  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba29  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba39  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba49  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba59  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba69  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba79  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba89  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; ba99  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; baa9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bab9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bac9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bad9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bae9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; baf9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb09  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb19  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb29  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb39  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb49  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb59  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb69  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb79  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb89  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bb99  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bba9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bbb9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bbc9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bbd9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bbe9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bbf9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc09  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc19  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc29  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc39  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc49  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc59  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc69  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc79  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc89  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bc99  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bca9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bcb9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bcc9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bcd9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bce9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bcf9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd09  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd19  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd29  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd39  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd49  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd59  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd69  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd79  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd89  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bd99  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bda9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bdb9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bdc9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bdd9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bde9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bdf9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be09  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be19  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be29  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be39  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be49  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be59  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be69  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be79  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be89  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; be99  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bea9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; beb9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bec9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bed9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bee9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bef9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf09  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf19  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf29  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf39  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf49  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf59  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf69  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf79  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf89  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bf99  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bfa9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bfb9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bfc9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bfd9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bfe9  ................
	defb 0ffh,0ffh,0ffh,0ffh,0ffh,0ffh,0ffh	; bff9
